// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: wabenet/dodo/configuration/v1alpha2/configuration.proto

package configurationv1alpha2

import (
	v1alpha21 "github.com/wabenet/dodo-core/internal/gen-proto/wabenet/dodo/build/v1alpha2"
	v1alpha22 "github.com/wabenet/dodo-core/internal/gen-proto/wabenet/dodo/plugin/v1alpha2"
	v1alpha2 "github.com/wabenet/dodo-core/internal/gen-proto/wabenet/dodo/runtime/v1alpha2"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListBackdropsResponse struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Backdrops *[]*Backdrop           `protobuf:"bytes,1,rep,name=backdrops"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ListBackdropsResponse) Reset() {
	*x = ListBackdropsResponse{}
	mi := &file_wabenet_dodo_configuration_v1alpha2_configuration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackdropsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackdropsResponse) ProtoMessage() {}

func (x *ListBackdropsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wabenet_dodo_configuration_v1alpha2_configuration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListBackdropsResponse) GetBackdrops() []*Backdrop {
	if x != nil {
		if x.xxx_hidden_Backdrops != nil {
			return *x.xxx_hidden_Backdrops
		}
	}
	return nil
}

func (x *ListBackdropsResponse) SetBackdrops(v []*Backdrop) {
	x.xxx_hidden_Backdrops = &v
}

type ListBackdropsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Backdrops []*Backdrop
}

func (b0 ListBackdropsResponse_builder) Build() *ListBackdropsResponse {
	m0 := &ListBackdropsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Backdrops = &b.Backdrops
	return m0
}

type GetBackdropRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Alias       *string                `protobuf:"bytes,1,opt,name=alias"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetBackdropRequest) Reset() {
	*x = GetBackdropRequest{}
	mi := &file_wabenet_dodo_configuration_v1alpha2_configuration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBackdropRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackdropRequest) ProtoMessage() {}

func (x *GetBackdropRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wabenet_dodo_configuration_v1alpha2_configuration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetBackdropRequest) GetAlias() string {
	if x != nil {
		if x.xxx_hidden_Alias != nil {
			return *x.xxx_hidden_Alias
		}
		return ""
	}
	return ""
}

func (x *GetBackdropRequest) SetAlias(v string) {
	x.xxx_hidden_Alias = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetBackdropRequest) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetBackdropRequest) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Alias = nil
}

type GetBackdropRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Alias *string
}

func (b0 GetBackdropRequest_builder) Build() *GetBackdropRequest {
	m0 := &GetBackdropRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Alias = b.Alias
	}
	return m0
}

type GetBackdropResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Backdrop *Backdrop              `protobuf:"bytes,1,opt,name=backdrop"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetBackdropResponse) Reset() {
	*x = GetBackdropResponse{}
	mi := &file_wabenet_dodo_configuration_v1alpha2_configuration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBackdropResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackdropResponse) ProtoMessage() {}

func (x *GetBackdropResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wabenet_dodo_configuration_v1alpha2_configuration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetBackdropResponse) GetBackdrop() *Backdrop {
	if x != nil {
		return x.xxx_hidden_Backdrop
	}
	return nil
}

func (x *GetBackdropResponse) SetBackdrop(v *Backdrop) {
	x.xxx_hidden_Backdrop = v
}

func (x *GetBackdropResponse) HasBackdrop() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Backdrop != nil
}

func (x *GetBackdropResponse) ClearBackdrop() {
	x.xxx_hidden_Backdrop = nil
}

type GetBackdropResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Backdrop *Backdrop
}

func (b0 GetBackdropResponse_builder) Build() *GetBackdropResponse {
	m0 := &GetBackdropResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Backdrop = b.Backdrop
	return m0
}

type Backdrop struct {
	state                      protoimpl.MessageState    `protogen:"opaque.v1"`
	xxx_hidden_Name            *string                   `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Aliases         []string                  `protobuf:"bytes,2,rep,name=aliases"`
	xxx_hidden_Runtime         *string                   `protobuf:"bytes,3,opt,name=runtime"`
	xxx_hidden_Builder         *string                   `protobuf:"bytes,4,opt,name=builder"`
	xxx_hidden_ContainerConfig *v1alpha2.ContainerConfig `protobuf:"bytes,5,opt,name=container_config,json=containerConfig"`
	xxx_hidden_BuildConfig     *v1alpha21.BuildConfig    `protobuf:"bytes,6,opt,name=build_config,json=buildConfig"`
	xxx_hidden_RequiredFiles   *[]*File                  `protobuf:"bytes,7,rep,name=requiredFiles"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *Backdrop) Reset() {
	*x = Backdrop{}
	mi := &file_wabenet_dodo_configuration_v1alpha2_configuration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Backdrop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Backdrop) ProtoMessage() {}

func (x *Backdrop) ProtoReflect() protoreflect.Message {
	mi := &file_wabenet_dodo_configuration_v1alpha2_configuration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Backdrop) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *Backdrop) GetAliases() []string {
	if x != nil {
		return x.xxx_hidden_Aliases
	}
	return nil
}

func (x *Backdrop) GetRuntime() string {
	if x != nil {
		if x.xxx_hidden_Runtime != nil {
			return *x.xxx_hidden_Runtime
		}
		return ""
	}
	return ""
}

func (x *Backdrop) GetBuilder() string {
	if x != nil {
		if x.xxx_hidden_Builder != nil {
			return *x.xxx_hidden_Builder
		}
		return ""
	}
	return ""
}

func (x *Backdrop) GetContainerConfig() *v1alpha2.ContainerConfig {
	if x != nil {
		return x.xxx_hidden_ContainerConfig
	}
	return nil
}

func (x *Backdrop) GetBuildConfig() *v1alpha21.BuildConfig {
	if x != nil {
		return x.xxx_hidden_BuildConfig
	}
	return nil
}

func (x *Backdrop) GetRequiredFiles() []*File {
	if x != nil {
		if x.xxx_hidden_RequiredFiles != nil {
			return *x.xxx_hidden_RequiredFiles
		}
	}
	return nil
}

func (x *Backdrop) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *Backdrop) SetAliases(v []string) {
	x.xxx_hidden_Aliases = v
}

func (x *Backdrop) SetRuntime(v string) {
	x.xxx_hidden_Runtime = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *Backdrop) SetBuilder(v string) {
	x.xxx_hidden_Builder = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *Backdrop) SetContainerConfig(v *v1alpha2.ContainerConfig) {
	x.xxx_hidden_ContainerConfig = v
}

func (x *Backdrop) SetBuildConfig(v *v1alpha21.BuildConfig) {
	x.xxx_hidden_BuildConfig = v
}

func (x *Backdrop) SetRequiredFiles(v []*File) {
	x.xxx_hidden_RequiredFiles = &v
}

func (x *Backdrop) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Backdrop) HasRuntime() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Backdrop) HasBuilder() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Backdrop) HasContainerConfig() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ContainerConfig != nil
}

func (x *Backdrop) HasBuildConfig() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_BuildConfig != nil
}

func (x *Backdrop) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *Backdrop) ClearRuntime() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Runtime = nil
}

func (x *Backdrop) ClearBuilder() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Builder = nil
}

func (x *Backdrop) ClearContainerConfig() {
	x.xxx_hidden_ContainerConfig = nil
}

func (x *Backdrop) ClearBuildConfig() {
	x.xxx_hidden_BuildConfig = nil
}

type Backdrop_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name            *string
	Aliases         []string
	Runtime         *string
	Builder         *string
	ContainerConfig *v1alpha2.ContainerConfig
	BuildConfig     *v1alpha21.BuildConfig
	RequiredFiles   []*File
}

func (b0 Backdrop_builder) Build() *Backdrop {
	m0 := &Backdrop{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_Name = b.Name
	}
	x.xxx_hidden_Aliases = b.Aliases
	if b.Runtime != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_Runtime = b.Runtime
	}
	if b.Builder != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_Builder = b.Builder
	}
	x.xxx_hidden_ContainerConfig = b.ContainerConfig
	x.xxx_hidden_BuildConfig = b.BuildConfig
	x.xxx_hidden_RequiredFiles = &b.RequiredFiles
	return m0
}

type File struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_FilePath    *string                `protobuf:"bytes,1,opt,name=file_path,json=filePath"`
	xxx_hidden_Contents    *string                `protobuf:"bytes,2,opt,name=contents"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_wabenet_dodo_configuration_v1alpha2_configuration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_wabenet_dodo_configuration_v1alpha2_configuration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *File) GetFilePath() string {
	if x != nil {
		if x.xxx_hidden_FilePath != nil {
			return *x.xxx_hidden_FilePath
		}
		return ""
	}
	return ""
}

func (x *File) GetContents() string {
	if x != nil {
		if x.xxx_hidden_Contents != nil {
			return *x.xxx_hidden_Contents
		}
		return ""
	}
	return ""
}

func (x *File) SetFilePath(v string) {
	x.xxx_hidden_FilePath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *File) SetContents(v string) {
	x.xxx_hidden_Contents = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *File) HasFilePath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *File) HasContents() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *File) ClearFilePath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_FilePath = nil
}

func (x *File) ClearContents() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Contents = nil
}

type File_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	FilePath *string
	Contents *string
}

func (b0 File_builder) Build() *File {
	m0 := &File{}
	b, x := &b0, m0
	_, _ = b, x
	if b.FilePath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_FilePath = b.FilePath
	}
	if b.Contents != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Contents = b.Contents
	}
	return m0
}

var File_wabenet_dodo_configuration_v1alpha2_configuration_proto protoreflect.FileDescriptor

const file_wabenet_dodo_configuration_v1alpha2_configuration_proto_rawDesc = "" +
	"\n" +
	"7wabenet/dodo/configuration/v1alpha2/configuration.proto\x12#wabenet.dodo.configuration.v1alpha2\x1a\x1bgoogle/protobuf/empty.proto\x1a)wabenet/dodo/plugin/v1alpha2/plugin.proto\x1a'wabenet/dodo/build/v1alpha2/build.proto\x1a+wabenet/dodo/runtime/v1alpha2/runtime.proto\"d\n" +
	"\x15ListBackdropsResponse\x12K\n" +
	"\tbackdrops\x18\x01 \x03(\v2-.wabenet.dodo.configuration.v1alpha2.BackdropR\tbackdrops\"*\n" +
	"\x12GetBackdropRequest\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\"`\n" +
	"\x13GetBackdropResponse\x12I\n" +
	"\bbackdrop\x18\x01 \x01(\v2-.wabenet.dodo.configuration.v1alpha2.BackdropR\bbackdrop\"\xe5\x02\n" +
	"\bBackdrop\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaliases\x18\x02 \x03(\tR\aaliases\x12\x18\n" +
	"\aruntime\x18\x03 \x01(\tR\aruntime\x12\x18\n" +
	"\abuilder\x18\x04 \x01(\tR\abuilder\x12Y\n" +
	"\x10container_config\x18\x05 \x01(\v2..wabenet.dodo.runtime.v1alpha2.ContainerConfigR\x0fcontainerConfig\x12K\n" +
	"\fbuild_config\x18\x06 \x01(\v2(.wabenet.dodo.build.v1alpha2.BuildConfigR\vbuildConfig\x12O\n" +
	"\rrequiredFiles\x18\a \x03(\v2).wabenet.dodo.configuration.v1alpha2.FileR\rrequiredFiles\"?\n" +
	"\x04File\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x1a\n" +
	"\bcontents\x18\x02 \x01(\tR\bcontents2\xe2\x03\n" +
	"\x06Plugin\x12Y\n" +
	"\x11GetPluginMetadata\x12\x16.google.protobuf.Empty\x1a,.wabenet.dodo.plugin.v1alpha2.PluginMetadata\x12V\n" +
	"\n" +
	"InitPlugin\x12\x16.google.protobuf.Empty\x1a0.wabenet.dodo.plugin.v1alpha2.InitPluginResponse\x12=\n" +
	"\vResetPlugin\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12c\n" +
	"\rListBackdrops\x12\x16.google.protobuf.Empty\x1a:.wabenet.dodo.configuration.v1alpha2.ListBackdropsResponse\x12\x80\x01\n" +
	"\vGetBackdrop\x127.wabenet.dodo.configuration.v1alpha2.GetBackdropRequest\x1a8.wabenet.dodo.configuration.v1alpha2.GetBackdropResponseB\xd7\x02\n" +
	"'com.wabenet.dodo.configuration.v1alpha2B\x12ConfigurationProtoP\x01Zigithub.com/wabenet/dodo-core/internal/gen-proto/wabenet/dodo/configuration/v1alpha2;configurationv1alpha2\xa2\x02\x03WDC\xaa\x02#Wabenet.Dodo.Configuration.V1alpha2\xca\x02#Wabenet\\Dodo\\Configuration\\V1alpha2\xe2\x02/Wabenet\\Dodo\\Configuration\\V1alpha2\\GPBMetadata\xea\x02&Wabenet::Dodo::Configuration::V1alpha2b\beditionsp\xe8\a"

var file_wabenet_dodo_configuration_v1alpha2_configuration_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_wabenet_dodo_configuration_v1alpha2_configuration_proto_goTypes = []any{
	(*ListBackdropsResponse)(nil),        // 0: wabenet.dodo.configuration.v1alpha2.ListBackdropsResponse
	(*GetBackdropRequest)(nil),           // 1: wabenet.dodo.configuration.v1alpha2.GetBackdropRequest
	(*GetBackdropResponse)(nil),          // 2: wabenet.dodo.configuration.v1alpha2.GetBackdropResponse
	(*Backdrop)(nil),                     // 3: wabenet.dodo.configuration.v1alpha2.Backdrop
	(*File)(nil),                         // 4: wabenet.dodo.configuration.v1alpha2.File
	(*v1alpha2.ContainerConfig)(nil),     // 5: wabenet.dodo.runtime.v1alpha2.ContainerConfig
	(*v1alpha21.BuildConfig)(nil),        // 6: wabenet.dodo.build.v1alpha2.BuildConfig
	(*emptypb.Empty)(nil),                // 7: google.protobuf.Empty
	(*v1alpha22.PluginMetadata)(nil),     // 8: wabenet.dodo.plugin.v1alpha2.PluginMetadata
	(*v1alpha22.InitPluginResponse)(nil), // 9: wabenet.dodo.plugin.v1alpha2.InitPluginResponse
}
var file_wabenet_dodo_configuration_v1alpha2_configuration_proto_depIdxs = []int32{
	3,  // 0: wabenet.dodo.configuration.v1alpha2.ListBackdropsResponse.backdrops:type_name -> wabenet.dodo.configuration.v1alpha2.Backdrop
	3,  // 1: wabenet.dodo.configuration.v1alpha2.GetBackdropResponse.backdrop:type_name -> wabenet.dodo.configuration.v1alpha2.Backdrop
	5,  // 2: wabenet.dodo.configuration.v1alpha2.Backdrop.container_config:type_name -> wabenet.dodo.runtime.v1alpha2.ContainerConfig
	6,  // 3: wabenet.dodo.configuration.v1alpha2.Backdrop.build_config:type_name -> wabenet.dodo.build.v1alpha2.BuildConfig
	4,  // 4: wabenet.dodo.configuration.v1alpha2.Backdrop.requiredFiles:type_name -> wabenet.dodo.configuration.v1alpha2.File
	7,  // 5: wabenet.dodo.configuration.v1alpha2.Plugin.GetPluginMetadata:input_type -> google.protobuf.Empty
	7,  // 6: wabenet.dodo.configuration.v1alpha2.Plugin.InitPlugin:input_type -> google.protobuf.Empty
	7,  // 7: wabenet.dodo.configuration.v1alpha2.Plugin.ResetPlugin:input_type -> google.protobuf.Empty
	7,  // 8: wabenet.dodo.configuration.v1alpha2.Plugin.ListBackdrops:input_type -> google.protobuf.Empty
	1,  // 9: wabenet.dodo.configuration.v1alpha2.Plugin.GetBackdrop:input_type -> wabenet.dodo.configuration.v1alpha2.GetBackdropRequest
	8,  // 10: wabenet.dodo.configuration.v1alpha2.Plugin.GetPluginMetadata:output_type -> wabenet.dodo.plugin.v1alpha2.PluginMetadata
	9,  // 11: wabenet.dodo.configuration.v1alpha2.Plugin.InitPlugin:output_type -> wabenet.dodo.plugin.v1alpha2.InitPluginResponse
	7,  // 12: wabenet.dodo.configuration.v1alpha2.Plugin.ResetPlugin:output_type -> google.protobuf.Empty
	0,  // 13: wabenet.dodo.configuration.v1alpha2.Plugin.ListBackdrops:output_type -> wabenet.dodo.configuration.v1alpha2.ListBackdropsResponse
	2,  // 14: wabenet.dodo.configuration.v1alpha2.Plugin.GetBackdrop:output_type -> wabenet.dodo.configuration.v1alpha2.GetBackdropResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_wabenet_dodo_configuration_v1alpha2_configuration_proto_init() }
func file_wabenet_dodo_configuration_v1alpha2_configuration_proto_init() {
	if File_wabenet_dodo_configuration_v1alpha2_configuration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wabenet_dodo_configuration_v1alpha2_configuration_proto_rawDesc), len(file_wabenet_dodo_configuration_v1alpha2_configuration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wabenet_dodo_configuration_v1alpha2_configuration_proto_goTypes,
		DependencyIndexes: file_wabenet_dodo_configuration_v1alpha2_configuration_proto_depIdxs,
		MessageInfos:      file_wabenet_dodo_configuration_v1alpha2_configuration_proto_msgTypes,
	}.Build()
	File_wabenet_dodo_configuration_v1alpha2_configuration_proto = out.File
	file_wabenet_dodo_configuration_v1alpha2_configuration_proto_goTypes = nil
	file_wabenet_dodo_configuration_v1alpha2_configuration_proto_depIdxs = nil
}
