// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: wabenet/dodo/configuration/v1alpha2/configuration.proto

package configurationv1alpha2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConfigurationPlugin_ListBackdrops_FullMethodName = "/wabenet.dodo.configuration.v1alpha2.ConfigurationPlugin/ListBackdrops"
	ConfigurationPlugin_GetBackdrop_FullMethodName   = "/wabenet.dodo.configuration.v1alpha2.ConfigurationPlugin/GetBackdrop"
)

// ConfigurationPluginClient is the client API for ConfigurationPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConfigurationPluginClient interface {
	ListBackdrops(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListBackdropsResponse, error)
	GetBackdrop(ctx context.Context, in *GetBackdropRequest, opts ...grpc.CallOption) (*GetBackdropResponse, error)
}

type configurationPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigurationPluginClient(cc grpc.ClientConnInterface) ConfigurationPluginClient {
	return &configurationPluginClient{cc}
}

func (c *configurationPluginClient) ListBackdrops(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListBackdropsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBackdropsResponse)
	err := c.cc.Invoke(ctx, ConfigurationPlugin_ListBackdrops_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configurationPluginClient) GetBackdrop(ctx context.Context, in *GetBackdropRequest, opts ...grpc.CallOption) (*GetBackdropResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBackdropResponse)
	err := c.cc.Invoke(ctx, ConfigurationPlugin_GetBackdrop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigurationPluginServer is the server API for ConfigurationPlugin service.
// All implementations must embed UnimplementedConfigurationPluginServer
// for forward compatibility.
type ConfigurationPluginServer interface {
	ListBackdrops(context.Context, *emptypb.Empty) (*ListBackdropsResponse, error)
	GetBackdrop(context.Context, *GetBackdropRequest) (*GetBackdropResponse, error)
	mustEmbedUnimplementedConfigurationPluginServer()
}

// UnimplementedConfigurationPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigurationPluginServer struct{}

func (UnimplementedConfigurationPluginServer) ListBackdrops(context.Context, *emptypb.Empty) (*ListBackdropsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBackdrops not implemented")
}
func (UnimplementedConfigurationPluginServer) GetBackdrop(context.Context, *GetBackdropRequest) (*GetBackdropResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBackdrop not implemented")
}
func (UnimplementedConfigurationPluginServer) mustEmbedUnimplementedConfigurationPluginServer() {}
func (UnimplementedConfigurationPluginServer) testEmbeddedByValue()                             {}

// UnsafeConfigurationPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigurationPluginServer will
// result in compilation errors.
type UnsafeConfigurationPluginServer interface {
	mustEmbedUnimplementedConfigurationPluginServer()
}

func RegisterConfigurationPluginServer(s grpc.ServiceRegistrar, srv ConfigurationPluginServer) {
	// If the following call panics, it indicates UnimplementedConfigurationPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigurationPlugin_ServiceDesc, srv)
}

func _ConfigurationPlugin_ListBackdrops_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigurationPluginServer).ListBackdrops(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigurationPlugin_ListBackdrops_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigurationPluginServer).ListBackdrops(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigurationPlugin_GetBackdrop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBackdropRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigurationPluginServer).GetBackdrop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigurationPlugin_GetBackdrop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigurationPluginServer).GetBackdrop(ctx, req.(*GetBackdropRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfigurationPlugin_ServiceDesc is the grpc.ServiceDesc for ConfigurationPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigurationPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wabenet.dodo.configuration.v1alpha2.ConfigurationPlugin",
	HandlerType: (*ConfigurationPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListBackdrops",
			Handler:    _ConfigurationPlugin_ListBackdrops_Handler,
		},
		{
			MethodName: "GetBackdrop",
			Handler:    _ConfigurationPlugin_GetBackdrop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wabenet/dodo/configuration/v1alpha2/configuration.proto",
}
