// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: wabenet/dodo/plugin/v1alpha2/plugin.proto

package pluginv1alpha2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OutputData_Channel int32

const (
	OutputData_CHANNEL_UNSPECIFIED OutputData_Channel = 0
	OutputData_CHANNEL_STDOUT      OutputData_Channel = 1
	OutputData_CHANNEL_STDERR      OutputData_Channel = 2
)

// Enum value maps for OutputData_Channel.
var (
	OutputData_Channel_name = map[int32]string{
		0: "CHANNEL_UNSPECIFIED",
		1: "CHANNEL_STDOUT",
		2: "CHANNEL_STDERR",
	}
	OutputData_Channel_value = map[string]int32{
		"CHANNEL_UNSPECIFIED": 0,
		"CHANNEL_STDOUT":      1,
		"CHANNEL_STDERR":      2,
	}
)

func (x OutputData_Channel) Enum() *OutputData_Channel {
	p := new(OutputData_Channel)
	*p = x
	return p
}

func (x OutputData_Channel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OutputData_Channel) Descriptor() protoreflect.EnumDescriptor {
	return file_wabenet_dodo_plugin_v1alpha2_plugin_proto_enumTypes[0].Descriptor()
}

func (OutputData_Channel) Type() protoreflect.EnumType {
	return &file_wabenet_dodo_plugin_v1alpha2_plugin_proto_enumTypes[0]
}

func (x OutputData_Channel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type PluginID struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type        *string                `protobuf:"bytes,1,opt,name=type"`
	xxx_hidden_Name        *string                `protobuf:"bytes,2,opt,name=name"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PluginID) Reset() {
	*x = PluginID{}
	mi := &file_wabenet_dodo_plugin_v1alpha2_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginID) ProtoMessage() {}

func (x *PluginID) ProtoReflect() protoreflect.Message {
	mi := &file_wabenet_dodo_plugin_v1alpha2_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PluginID) GetType() string {
	if x != nil {
		if x.xxx_hidden_Type != nil {
			return *x.xxx_hidden_Type
		}
		return ""
	}
	return ""
}

func (x *PluginID) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *PluginID) SetType(v string) {
	x.xxx_hidden_Type = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *PluginID) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *PluginID) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *PluginID) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *PluginID) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Type = nil
}

func (x *PluginID) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

type PluginID_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Type *string
	Name *string
}

func (b0 PluginID_builder) Build() *PluginID {
	m0 := &PluginID{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Type = b.Type
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Name = b.Name
	}
	return m0
}

type PluginMetadata struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id           *PluginID              `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Dependencies *[]*PluginID           `protobuf:"bytes,2,rep,name=dependencies"`
	xxx_hidden_Labels       map[string]string      `protobuf:"bytes,3,rep,name=labels" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *PluginMetadata) Reset() {
	*x = PluginMetadata{}
	mi := &file_wabenet_dodo_plugin_v1alpha2_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginMetadata) ProtoMessage() {}

func (x *PluginMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_wabenet_dodo_plugin_v1alpha2_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PluginMetadata) GetId() *PluginID {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *PluginMetadata) GetDependencies() []*PluginID {
	if x != nil {
		if x.xxx_hidden_Dependencies != nil {
			return *x.xxx_hidden_Dependencies
		}
	}
	return nil
}

func (x *PluginMetadata) GetLabels() map[string]string {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return nil
}

func (x *PluginMetadata) SetId(v *PluginID) {
	x.xxx_hidden_Id = v
}

func (x *PluginMetadata) SetDependencies(v []*PluginID) {
	x.xxx_hidden_Dependencies = &v
}

func (x *PluginMetadata) SetLabels(v map[string]string) {
	x.xxx_hidden_Labels = v
}

func (x *PluginMetadata) HasId() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Id != nil
}

func (x *PluginMetadata) ClearId() {
	x.xxx_hidden_Id = nil
}

type PluginMetadata_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id           *PluginID
	Dependencies []*PluginID
	Labels       map[string]string
}

func (b0 PluginMetadata_builder) Build() *PluginMetadata {
	m0 := &PluginMetadata{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Dependencies = &b.Dependencies
	x.xxx_hidden_Labels = b.Labels
	return m0
}

type PluginConfig struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Config map[string]string      `protobuf:"bytes,1,rep,name=config" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PluginConfig) Reset() {
	*x = PluginConfig{}
	mi := &file_wabenet_dodo_plugin_v1alpha2_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginConfig) ProtoMessage() {}

func (x *PluginConfig) ProtoReflect() protoreflect.Message {
	mi := &file_wabenet_dodo_plugin_v1alpha2_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PluginConfig) GetConfig() map[string]string {
	if x != nil {
		return x.xxx_hidden_Config
	}
	return nil
}

func (x *PluginConfig) SetConfig(v map[string]string) {
	x.xxx_hidden_Config = v
}

type PluginConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Config map[string]string
}

func (b0 PluginConfig_builder) Build() *PluginConfig {
	m0 := &PluginConfig{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Config = b.Config
	return m0
}

type InitialStreamInput struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *InitialStreamInput) Reset() {
	*x = InitialStreamInput{}
	mi := &file_wabenet_dodo_plugin_v1alpha2_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitialStreamInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialStreamInput) ProtoMessage() {}

func (x *InitialStreamInput) ProtoReflect() protoreflect.Message {
	mi := &file_wabenet_dodo_plugin_v1alpha2_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *InitialStreamInput) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *InitialStreamInput) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *InitialStreamInput) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *InitialStreamInput) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

type InitialStreamInput_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *string
}

func (b0 InitialStreamInput_builder) Build() *InitialStreamInput {
	m0 := &InitialStreamInput{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = b.Id
	}
	return m0
}

type InputData struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Data        []byte                 `protobuf:"bytes,1,opt,name=data"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *InputData) Reset() {
	*x = InputData{}
	mi := &file_wabenet_dodo_plugin_v1alpha2_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputData) ProtoMessage() {}

func (x *InputData) ProtoReflect() protoreflect.Message {
	mi := &file_wabenet_dodo_plugin_v1alpha2_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *InputData) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *InputData) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *InputData) HasData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *InputData) ClearData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Data = nil
}

type InputData_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Data []byte
}

func (b0 InputData_builder) Build() *InputData {
	m0 := &InputData{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Data != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Data = b.Data
	}
	return m0
}

type OutputData struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Channel     OutputData_Channel     `protobuf:"varint,1,opt,name=channel,enum=wabenet.dodo.plugin.v1alpha2.OutputData_Channel"`
	xxx_hidden_Data        []byte                 `protobuf:"bytes,2,opt,name=data"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *OutputData) Reset() {
	*x = OutputData{}
	mi := &file_wabenet_dodo_plugin_v1alpha2_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputData) ProtoMessage() {}

func (x *OutputData) ProtoReflect() protoreflect.Message {
	mi := &file_wabenet_dodo_plugin_v1alpha2_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OutputData) GetChannel() OutputData_Channel {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Channel
		}
	}
	return OutputData_CHANNEL_UNSPECIFIED
}

func (x *OutputData) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *OutputData) SetChannel(v OutputData_Channel) {
	x.xxx_hidden_Channel = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *OutputData) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *OutputData) HasChannel() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *OutputData) HasData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *OutputData) ClearChannel() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Channel = OutputData_CHANNEL_UNSPECIFIED
}

func (x *OutputData) ClearData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Data = nil
}

type OutputData_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Channel *OutputData_Channel
	Data    []byte
}

func (b0 OutputData_builder) Build() *OutputData {
	m0 := &OutputData{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Channel != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Channel = *b.Channel
	}
	if b.Data != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Data = b.Data
	}
	return m0
}

var File_wabenet_dodo_plugin_v1alpha2_plugin_proto protoreflect.FileDescriptor

const file_wabenet_dodo_plugin_v1alpha2_plugin_proto_rawDesc = "" +
	"\n" +
	")wabenet/dodo/plugin/v1alpha2/plugin.proto\x12\x1cwabenet.dodo.plugin.v1alpha2\"2\n" +
	"\bPluginID\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xa1\x02\n" +
	"\x0ePluginMetadata\x126\n" +
	"\x02id\x18\x01 \x01(\v2&.wabenet.dodo.plugin.v1alpha2.PluginIDR\x02id\x12J\n" +
	"\fdependencies\x18\x02 \x03(\v2&.wabenet.dodo.plugin.v1alpha2.PluginIDR\fdependencies\x12P\n" +
	"\x06labels\x18\x03 \x03(\v28.wabenet.dodo.plugin.v1alpha2.PluginMetadata.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x99\x01\n" +
	"\fPluginConfig\x12N\n" +
	"\x06config\x18\x01 \x03(\v26.wabenet.dodo.plugin.v1alpha2.PluginConfig.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"$\n" +
	"\x12InitialStreamInput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1f\n" +
	"\tInputData\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\xb8\x01\n" +
	"\n" +
	"OutputData\x12J\n" +
	"\achannel\x18\x01 \x01(\x0e20.wabenet.dodo.plugin.v1alpha2.OutputData.ChannelR\achannel\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"J\n" +
	"\aChannel\x12\x17\n" +
	"\x13CHANNEL_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eCHANNEL_STDOUT\x10\x01\x12\x12\n" +
	"\x0eCHANNEL_STDERR\x10\x02B\x9f\x02\n" +
	" com.wabenet.dodo.plugin.v1alpha2B\vPluginProtoP\x01Z[github.com/wabenet/dodo-core/internal/gen-proto/wabenet/dodo/plugin/v1alpha2;pluginv1alpha2\xa2\x02\x03WDP\xaa\x02\x1cWabenet.Dodo.Plugin.V1alpha2\xca\x02\x1cWabenet\\Dodo\\Plugin\\V1alpha2\xe2\x02(Wabenet\\Dodo\\Plugin\\V1alpha2\\GPBMetadata\xea\x02\x1fWabenet::Dodo::Plugin::V1alpha2b\beditionsp\xe8\a"

var file_wabenet_dodo_plugin_v1alpha2_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wabenet_dodo_plugin_v1alpha2_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_wabenet_dodo_plugin_v1alpha2_plugin_proto_goTypes = []any{
	(OutputData_Channel)(0),    // 0: wabenet.dodo.plugin.v1alpha2.OutputData.Channel
	(*PluginID)(nil),           // 1: wabenet.dodo.plugin.v1alpha2.PluginID
	(*PluginMetadata)(nil),     // 2: wabenet.dodo.plugin.v1alpha2.PluginMetadata
	(*PluginConfig)(nil),       // 3: wabenet.dodo.plugin.v1alpha2.PluginConfig
	(*InitialStreamInput)(nil), // 4: wabenet.dodo.plugin.v1alpha2.InitialStreamInput
	(*InputData)(nil),          // 5: wabenet.dodo.plugin.v1alpha2.InputData
	(*OutputData)(nil),         // 6: wabenet.dodo.plugin.v1alpha2.OutputData
	nil,                        // 7: wabenet.dodo.plugin.v1alpha2.PluginMetadata.LabelsEntry
	nil,                        // 8: wabenet.dodo.plugin.v1alpha2.PluginConfig.ConfigEntry
}
var file_wabenet_dodo_plugin_v1alpha2_plugin_proto_depIdxs = []int32{
	1, // 0: wabenet.dodo.plugin.v1alpha2.PluginMetadata.id:type_name -> wabenet.dodo.plugin.v1alpha2.PluginID
	1, // 1: wabenet.dodo.plugin.v1alpha2.PluginMetadata.dependencies:type_name -> wabenet.dodo.plugin.v1alpha2.PluginID
	7, // 2: wabenet.dodo.plugin.v1alpha2.PluginMetadata.labels:type_name -> wabenet.dodo.plugin.v1alpha2.PluginMetadata.LabelsEntry
	8, // 3: wabenet.dodo.plugin.v1alpha2.PluginConfig.config:type_name -> wabenet.dodo.plugin.v1alpha2.PluginConfig.ConfigEntry
	0, // 4: wabenet.dodo.plugin.v1alpha2.OutputData.channel:type_name -> wabenet.dodo.plugin.v1alpha2.OutputData.Channel
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_wabenet_dodo_plugin_v1alpha2_plugin_proto_init() }
func file_wabenet_dodo_plugin_v1alpha2_plugin_proto_init() {
	if File_wabenet_dodo_plugin_v1alpha2_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wabenet_dodo_plugin_v1alpha2_plugin_proto_rawDesc), len(file_wabenet_dodo_plugin_v1alpha2_plugin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wabenet_dodo_plugin_v1alpha2_plugin_proto_goTypes,
		DependencyIndexes: file_wabenet_dodo_plugin_v1alpha2_plugin_proto_depIdxs,
		EnumInfos:         file_wabenet_dodo_plugin_v1alpha2_plugin_proto_enumTypes,
		MessageInfos:      file_wabenet_dodo_plugin_v1alpha2_plugin_proto_msgTypes,
	}.Build()
	File_wabenet_dodo_plugin_v1alpha2_plugin_proto = out.File
	file_wabenet_dodo_plugin_v1alpha2_plugin_proto_goTypes = nil
	file_wabenet_dodo_plugin_v1alpha2_plugin_proto_depIdxs = nil
}
