# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.3.12
_src_path: https://github.com/wabenet/project-template
archetype: other
archetype_other: custom
components:
- protobuf
custom_components:
- plugin
description: This repository contains the core components and plugin system for the
    dodo project.
lifecycle: production
name: dodo-core

