---
linters:
  enable-all: true
  disable:
    - exhaustivestruct

linters-settings:
  gofumpt:
    extra-rules: true

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - gochecknoglobals
        - unused
