---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dodo-core
  description: Core components for the dodo plugin ecosystem

spec:
  type: library
  lifecycle: production
  owner: ole.claussen@wabenet.com
