// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: plugin/v1alpha2/plugin.proto

package plugin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OutputData_Channel int32

const (
	OutputData_INVALID OutputData_Channel = 0
	OutputData_STDOUT  OutputData_Channel = 1
	OutputData_STDERR  OutputData_Channel = 2
)

// Enum value maps for OutputData_Channel.
var (
	OutputData_Channel_name = map[int32]string{
		0: "INVALID",
		1: "STDOUT",
		2: "STDERR",
	}
	OutputData_Channel_value = map[string]int32{
		"INVALID": 0,
		"STDOUT":  1,
		"STDERR":  2,
	}
)

func (x OutputData_Channel) Enum() *OutputData_Channel {
	p := new(OutputData_Channel)
	*p = x
	return p
}

func (x OutputData_Channel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OutputData_Channel) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_v1alpha2_plugin_proto_enumTypes[0].Descriptor()
}

func (OutputData_Channel) Type() protoreflect.EnumType {
	return &file_plugin_v1alpha2_plugin_proto_enumTypes[0]
}

func (x OutputData_Channel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type PluginID struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type        *string                `protobuf:"bytes,1,opt,name=type"`
	xxx_hidden_Name        *string                `protobuf:"bytes,2,opt,name=name"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PluginID) Reset() {
	*x = PluginID{}
	mi := &file_plugin_v1alpha2_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginID) ProtoMessage() {}

func (x *PluginID) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1alpha2_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PluginID) GetType() string {
	if x != nil {
		if x.xxx_hidden_Type != nil {
			return *x.xxx_hidden_Type
		}
		return ""
	}
	return ""
}

func (x *PluginID) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *PluginID) SetType(v string) {
	x.xxx_hidden_Type = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *PluginID) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *PluginID) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *PluginID) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *PluginID) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Type = nil
}

func (x *PluginID) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

type PluginID_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Type *string
	Name *string
}

func (b0 PluginID_builder) Build() *PluginID {
	m0 := &PluginID{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Type = b.Type
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Name = b.Name
	}
	return m0
}

type PluginMetadata struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id           *PluginID              `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Dependencies *[]*PluginID           `protobuf:"bytes,2,rep,name=dependencies"`
	xxx_hidden_Labels       map[string]string      `protobuf:"bytes,3,rep,name=labels" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *PluginMetadata) Reset() {
	*x = PluginMetadata{}
	mi := &file_plugin_v1alpha2_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginMetadata) ProtoMessage() {}

func (x *PluginMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1alpha2_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PluginMetadata) GetId() *PluginID {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *PluginMetadata) GetDependencies() []*PluginID {
	if x != nil {
		if x.xxx_hidden_Dependencies != nil {
			return *x.xxx_hidden_Dependencies
		}
	}
	return nil
}

func (x *PluginMetadata) GetLabels() map[string]string {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return nil
}

func (x *PluginMetadata) SetId(v *PluginID) {
	x.xxx_hidden_Id = v
}

func (x *PluginMetadata) SetDependencies(v []*PluginID) {
	x.xxx_hidden_Dependencies = &v
}

func (x *PluginMetadata) SetLabels(v map[string]string) {
	x.xxx_hidden_Labels = v
}

func (x *PluginMetadata) HasId() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Id != nil
}

func (x *PluginMetadata) ClearId() {
	x.xxx_hidden_Id = nil
}

type PluginMetadata_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id           *PluginID
	Dependencies []*PluginID
	Labels       map[string]string
}

func (b0 PluginMetadata_builder) Build() *PluginMetadata {
	m0 := &PluginMetadata{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Dependencies = &b.Dependencies
	x.xxx_hidden_Labels = b.Labels
	return m0
}

type InitPluginResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Config map[string]string      `protobuf:"bytes,1,rep,name=config" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InitPluginResponse) Reset() {
	*x = InitPluginResponse{}
	mi := &file_plugin_v1alpha2_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitPluginResponse) ProtoMessage() {}

func (x *InitPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1alpha2_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *InitPluginResponse) GetConfig() map[string]string {
	if x != nil {
		return x.xxx_hidden_Config
	}
	return nil
}

func (x *InitPluginResponse) SetConfig(v map[string]string) {
	x.xxx_hidden_Config = v
}

type InitPluginResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Config map[string]string
}

func (b0 InitPluginResponse_builder) Build() *InitPluginResponse {
	m0 := &InitPluginResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Config = b.Config
	return m0
}

type InputData struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Data        []byte                 `protobuf:"bytes,1,opt,name=data"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *InputData) Reset() {
	*x = InputData{}
	mi := &file_plugin_v1alpha2_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputData) ProtoMessage() {}

func (x *InputData) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1alpha2_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *InputData) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *InputData) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *InputData) HasData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *InputData) ClearData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Data = nil
}

type InputData_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Data []byte
}

func (b0 InputData_builder) Build() *InputData {
	m0 := &InputData{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Data != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Data = b.Data
	}
	return m0
}

type OutputData struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Channel     OutputData_Channel     `protobuf:"varint,1,opt,name=channel,enum=com.wabenet.dodo.plugin.v1alpha2.OutputData_Channel"`
	xxx_hidden_Data        []byte                 `protobuf:"bytes,2,opt,name=data"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *OutputData) Reset() {
	*x = OutputData{}
	mi := &file_plugin_v1alpha2_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputData) ProtoMessage() {}

func (x *OutputData) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1alpha2_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OutputData) GetChannel() OutputData_Channel {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Channel
		}
	}
	return OutputData_INVALID
}

func (x *OutputData) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *OutputData) SetChannel(v OutputData_Channel) {
	x.xxx_hidden_Channel = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *OutputData) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *OutputData) HasChannel() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *OutputData) HasData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *OutputData) ClearChannel() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Channel = OutputData_INVALID
}

func (x *OutputData) ClearData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Data = nil
}

type OutputData_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Channel *OutputData_Channel
	Data    []byte
}

func (b0 OutputData_builder) Build() *OutputData {
	m0 := &OutputData{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Channel != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Channel = *b.Channel
	}
	if b.Data != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Data = b.Data
	}
	return m0
}

type StreamInputRequest struct {
	state                       protoimpl.MessageState                `protogen:"opaque.v1"`
	xxx_hidden_InputRequestType isStreamInputRequest_InputRequestType `protobuf_oneof:"input_request_type"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *StreamInputRequest) Reset() {
	*x = StreamInputRequest{}
	mi := &file_plugin_v1alpha2_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamInputRequest) ProtoMessage() {}

func (x *StreamInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1alpha2_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StreamInputRequest) GetInitialRequest() *InitialStreamInputRequest {
	if x != nil {
		if x, ok := x.xxx_hidden_InputRequestType.(*streamInputRequest_InitialRequest); ok {
			return x.InitialRequest
		}
	}
	return nil
}

func (x *StreamInputRequest) GetInputData() *InputData {
	if x != nil {
		if x, ok := x.xxx_hidden_InputRequestType.(*streamInputRequest_InputData); ok {
			return x.InputData
		}
	}
	return nil
}

func (x *StreamInputRequest) SetInitialRequest(v *InitialStreamInputRequest) {
	if v == nil {
		x.xxx_hidden_InputRequestType = nil
		return
	}
	x.xxx_hidden_InputRequestType = &streamInputRequest_InitialRequest{v}
}

func (x *StreamInputRequest) SetInputData(v *InputData) {
	if v == nil {
		x.xxx_hidden_InputRequestType = nil
		return
	}
	x.xxx_hidden_InputRequestType = &streamInputRequest_InputData{v}
}

func (x *StreamInputRequest) HasInputRequestType() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_InputRequestType != nil
}

func (x *StreamInputRequest) HasInitialRequest() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_InputRequestType.(*streamInputRequest_InitialRequest)
	return ok
}

func (x *StreamInputRequest) HasInputData() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_InputRequestType.(*streamInputRequest_InputData)
	return ok
}

func (x *StreamInputRequest) ClearInputRequestType() {
	x.xxx_hidden_InputRequestType = nil
}

func (x *StreamInputRequest) ClearInitialRequest() {
	if _, ok := x.xxx_hidden_InputRequestType.(*streamInputRequest_InitialRequest); ok {
		x.xxx_hidden_InputRequestType = nil
	}
}

func (x *StreamInputRequest) ClearInputData() {
	if _, ok := x.xxx_hidden_InputRequestType.(*streamInputRequest_InputData); ok {
		x.xxx_hidden_InputRequestType = nil
	}
}

const StreamInputRequest_InputRequestType_not_set_case case_StreamInputRequest_InputRequestType = 0
const StreamInputRequest_InitialRequest_case case_StreamInputRequest_InputRequestType = 1
const StreamInputRequest_InputData_case case_StreamInputRequest_InputRequestType = 2

func (x *StreamInputRequest) WhichInputRequestType() case_StreamInputRequest_InputRequestType {
	if x == nil {
		return StreamInputRequest_InputRequestType_not_set_case
	}
	switch x.xxx_hidden_InputRequestType.(type) {
	case *streamInputRequest_InitialRequest:
		return StreamInputRequest_InitialRequest_case
	case *streamInputRequest_InputData:
		return StreamInputRequest_InputData_case
	default:
		return StreamInputRequest_InputRequestType_not_set_case
	}
}

type StreamInputRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_InputRequestType:
	InitialRequest *InitialStreamInputRequest
	InputData      *InputData
	// -- end of xxx_hidden_InputRequestType
}

func (b0 StreamInputRequest_builder) Build() *StreamInputRequest {
	m0 := &StreamInputRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.InitialRequest != nil {
		x.xxx_hidden_InputRequestType = &streamInputRequest_InitialRequest{b.InitialRequest}
	}
	if b.InputData != nil {
		x.xxx_hidden_InputRequestType = &streamInputRequest_InputData{b.InputData}
	}
	return m0
}

type case_StreamInputRequest_InputRequestType protoreflect.FieldNumber

func (x case_StreamInputRequest_InputRequestType) String() string {
	md := file_plugin_v1alpha2_plugin_proto_msgTypes[5].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isStreamInputRequest_InputRequestType interface {
	isStreamInputRequest_InputRequestType()
}

type streamInputRequest_InitialRequest struct {
	InitialRequest *InitialStreamInputRequest `protobuf:"bytes,1,opt,name=initial_request,json=initialRequest,oneof"`
}

type streamInputRequest_InputData struct {
	InputData *InputData `protobuf:"bytes,2,opt,name=input_data,json=inputData,oneof"`
}

func (*streamInputRequest_InitialRequest) isStreamInputRequest_InputRequestType() {}

func (*streamInputRequest_InputData) isStreamInputRequest_InputRequestType() {}

type InitialStreamInputRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *InitialStreamInputRequest) Reset() {
	*x = InitialStreamInputRequest{}
	mi := &file_plugin_v1alpha2_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitialStreamInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialStreamInputRequest) ProtoMessage() {}

func (x *InitialStreamInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1alpha2_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *InitialStreamInputRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *InitialStreamInputRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *InitialStreamInputRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *InitialStreamInputRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

type InitialStreamInputRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *string
}

func (b0 InitialStreamInputRequest_builder) Build() *InitialStreamInputRequest {
	m0 := &InitialStreamInputRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = b.Id
	}
	return m0
}

type StreamOutputRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StreamOutputRequest) Reset() {
	*x = StreamOutputRequest{}
	mi := &file_plugin_v1alpha2_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOutputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOutputRequest) ProtoMessage() {}

func (x *StreamOutputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1alpha2_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StreamOutputRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *StreamOutputRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *StreamOutputRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *StreamOutputRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

type StreamOutputRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *string
}

func (b0 StreamOutputRequest_builder) Build() *StreamOutputRequest {
	m0 := &StreamOutputRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = b.Id
	}
	return m0
}

var File_plugin_v1alpha2_plugin_proto protoreflect.FileDescriptor

const file_plugin_v1alpha2_plugin_proto_rawDesc = "" +
	"\n" +
	"\x1cplugin/v1alpha2/plugin.proto\x12 com.wabenet.dodo.plugin.v1alpha2\x1a!google/protobuf/go_features.proto\"2\n" +
	"\bPluginID\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xad\x02\n" +
	"\x0ePluginMetadata\x12:\n" +
	"\x02id\x18\x01 \x01(\v2*.com.wabenet.dodo.plugin.v1alpha2.PluginIDR\x02id\x12N\n" +
	"\fdependencies\x18\x02 \x03(\v2*.com.wabenet.dodo.plugin.v1alpha2.PluginIDR\fdependencies\x12T\n" +
	"\x06labels\x18\x03 \x03(\v2<.com.wabenet.dodo.plugin.v1alpha2.PluginMetadata.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa9\x01\n" +
	"\x12InitPluginResponse\x12X\n" +
	"\x06config\x18\x01 \x03(\v2@.com.wabenet.dodo.plugin.v1alpha2.InitPluginResponse.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x1f\n" +
	"\tInputData\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\xa0\x01\n" +
	"\n" +
	"OutputData\x12N\n" +
	"\achannel\x18\x01 \x01(\x0e24.com.wabenet.dodo.plugin.v1alpha2.OutputData.ChannelR\achannel\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\".\n" +
	"\aChannel\x12\v\n" +
	"\aINVALID\x10\x00\x12\n" +
	"\n" +
	"\x06STDOUT\x10\x01\x12\n" +
	"\n" +
	"\x06STDERR\x10\x02\"\xe0\x01\n" +
	"\x12StreamInputRequest\x12f\n" +
	"\x0finitial_request\x18\x01 \x01(\v2;.com.wabenet.dodo.plugin.v1alpha2.InitialStreamInputRequestH\x00R\x0einitialRequest\x12L\n" +
	"\n" +
	"input_data\x18\x02 \x01(\v2+.com.wabenet.dodo.plugin.v1alpha2.InputDataH\x00R\tinputDataB\x14\n" +
	"\x12input_request_type\"+\n" +
	"\x19InitialStreamInputRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"%\n" +
	"\x13StreamOutputRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02idBAZ7github.com/wabenet/dodo-core/api/plugin/v1alpha2;plugin\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_plugin_v1alpha2_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_plugin_v1alpha2_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_plugin_v1alpha2_plugin_proto_goTypes = []any{
	(OutputData_Channel)(0),           // 0: com.wabenet.dodo.plugin.v1alpha2.OutputData.Channel
	(*PluginID)(nil),                  // 1: com.wabenet.dodo.plugin.v1alpha2.PluginID
	(*PluginMetadata)(nil),            // 2: com.wabenet.dodo.plugin.v1alpha2.PluginMetadata
	(*InitPluginResponse)(nil),        // 3: com.wabenet.dodo.plugin.v1alpha2.InitPluginResponse
	(*InputData)(nil),                 // 4: com.wabenet.dodo.plugin.v1alpha2.InputData
	(*OutputData)(nil),                // 5: com.wabenet.dodo.plugin.v1alpha2.OutputData
	(*StreamInputRequest)(nil),        // 6: com.wabenet.dodo.plugin.v1alpha2.StreamInputRequest
	(*InitialStreamInputRequest)(nil), // 7: com.wabenet.dodo.plugin.v1alpha2.InitialStreamInputRequest
	(*StreamOutputRequest)(nil),       // 8: com.wabenet.dodo.plugin.v1alpha2.StreamOutputRequest
	nil,                               // 9: com.wabenet.dodo.plugin.v1alpha2.PluginMetadata.LabelsEntry
	nil,                               // 10: com.wabenet.dodo.plugin.v1alpha2.InitPluginResponse.ConfigEntry
}
var file_plugin_v1alpha2_plugin_proto_depIdxs = []int32{
	1,  // 0: com.wabenet.dodo.plugin.v1alpha2.PluginMetadata.id:type_name -> com.wabenet.dodo.plugin.v1alpha2.PluginID
	1,  // 1: com.wabenet.dodo.plugin.v1alpha2.PluginMetadata.dependencies:type_name -> com.wabenet.dodo.plugin.v1alpha2.PluginID
	9,  // 2: com.wabenet.dodo.plugin.v1alpha2.PluginMetadata.labels:type_name -> com.wabenet.dodo.plugin.v1alpha2.PluginMetadata.LabelsEntry
	10, // 3: com.wabenet.dodo.plugin.v1alpha2.InitPluginResponse.config:type_name -> com.wabenet.dodo.plugin.v1alpha2.InitPluginResponse.ConfigEntry
	0,  // 4: com.wabenet.dodo.plugin.v1alpha2.OutputData.channel:type_name -> com.wabenet.dodo.plugin.v1alpha2.OutputData.Channel
	7,  // 5: com.wabenet.dodo.plugin.v1alpha2.StreamInputRequest.initial_request:type_name -> com.wabenet.dodo.plugin.v1alpha2.InitialStreamInputRequest
	4,  // 6: com.wabenet.dodo.plugin.v1alpha2.StreamInputRequest.input_data:type_name -> com.wabenet.dodo.plugin.v1alpha2.InputData
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_plugin_v1alpha2_plugin_proto_init() }
func file_plugin_v1alpha2_plugin_proto_init() {
	if File_plugin_v1alpha2_plugin_proto != nil {
		return
	}
	file_plugin_v1alpha2_plugin_proto_msgTypes[5].OneofWrappers = []any{
		(*streamInputRequest_InitialRequest)(nil),
		(*streamInputRequest_InputData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_v1alpha2_plugin_proto_rawDesc), len(file_plugin_v1alpha2_plugin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plugin_v1alpha2_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_v1alpha2_plugin_proto_depIdxs,
		EnumInfos:         file_plugin_v1alpha2_plugin_proto_enumTypes,
		MessageInfos:      file_plugin_v1alpha2_plugin_proto_msgTypes,
	}.Build()
	File_plugin_v1alpha2_plugin_proto = out.File
	file_plugin_v1alpha2_plugin_proto_goTypes = nil
	file_plugin_v1alpha2_plugin_proto_depIdxs = nil
}
