// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/plugin/configuration/proto/configuration.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
	types "github.com/oclaussen/dodo/pkg/types"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8182450cf75192a, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Container struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8182450cf75192a, []int{1}
}

func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (m *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(m, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Backdrop struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Backdrop) Reset()         { *m = Backdrop{} }
func (m *Backdrop) String() string { return proto.CompactTextString(m) }
func (*Backdrop) ProtoMessage()    {}
func (*Backdrop) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8182450cf75192a, []int{2}
}

func (m *Backdrop) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Backdrop.Unmarshal(m, b)
}
func (m *Backdrop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Backdrop.Marshal(b, m, deterministic)
}
func (m *Backdrop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Backdrop.Merge(m, src)
}
func (m *Backdrop) XXX_Size() int {
	return xxx_messageInfo_Backdrop.Size(m)
}
func (m *Backdrop) XXX_DiscardUnknown() {
	xxx_messageInfo_Backdrop.DiscardUnknown(m)
}

var xxx_messageInfo_Backdrop proto.InternalMessageInfo

func (m *Backdrop) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ClientOptions struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Host                 string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	CaFile               string   `protobuf:"bytes,3,opt,name=ca_file,json=caFile,proto3" json:"ca_file,omitempty"`
	CertFile             string   `protobuf:"bytes,4,opt,name=cert_file,json=certFile,proto3" json:"cert_file,omitempty"`
	KeyFile              string   `protobuf:"bytes,5,opt,name=key_file,json=keyFile,proto3" json:"key_file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientOptions) Reset()         { *m = ClientOptions{} }
func (m *ClientOptions) String() string { return proto.CompactTextString(m) }
func (*ClientOptions) ProtoMessage()    {}
func (*ClientOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8182450cf75192a, []int{3}
}

func (m *ClientOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientOptions.Unmarshal(m, b)
}
func (m *ClientOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientOptions.Marshal(b, m, deterministic)
}
func (m *ClientOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientOptions.Merge(m, src)
}
func (m *ClientOptions) XXX_Size() int {
	return xxx_messageInfo_ClientOptions.Size(m)
}
func (m *ClientOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientOptions.DiscardUnknown(m)
}

var xxx_messageInfo_ClientOptions proto.InternalMessageInfo

func (m *ClientOptions) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ClientOptions) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *ClientOptions) GetCaFile() string {
	if m != nil {
		return m.CaFile
	}
	return ""
}

func (m *ClientOptions) GetCertFile() string {
	if m != nil {
		return m.CertFile
	}
	return ""
}

func (m *ClientOptions) GetKeyFile() string {
	if m != nil {
		return m.KeyFile
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "proto.Empty")
	proto.RegisterType((*Container)(nil), "proto.Container")
	proto.RegisterType((*Backdrop)(nil), "proto.Backdrop")
	proto.RegisterType((*ClientOptions)(nil), "proto.ClientOptions")
}

func init() {
	proto.RegisterFile("pkg/plugin/configuration/proto/configuration.proto", fileDescriptor_e8182450cf75192a)
}

var fileDescriptor_e8182450cf75192a = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x51, 0x5f, 0x4b, 0xfb, 0x30,
	0x14, 0x65, 0xfd, 0xad, 0x6b, 0x7b, 0xf9, 0xe9, 0x46, 0x54, 0xac, 0x1d, 0x88, 0xf4, 0x49, 0x10,
	0x5a, 0x98, 0x0f, 0xe2, 0xab, 0x43, 0x7d, 0x54, 0x04, 0x9f, 0x25, 0xb6, 0x77, 0x35, 0xb4, 0x4b,
	0x42, 0x9a, 0x0d, 0xfa, 0x25, 0xfc, 0x2c, 0x7e, 0x44, 0x49, 0xd2, 0x8a, 0xf5, 0xa5, 0xbd, 0xf7,
	0x9c, 0x7b, 0xee, 0x9f, 0x13, 0x58, 0xc9, 0xba, 0xca, 0x65, 0xb3, 0xab, 0x18, 0xcf, 0x0b, 0xc1,
	0x37, 0xac, 0xda, 0x29, 0xaa, 0x99, 0xe0, 0xb9, 0x54, 0x42, 0x8b, 0x31, 0x96, 0x59, 0x8c, 0xf8,
	0xf6, 0x97, 0x9c, 0x18, 0xa9, 0xee, 0x24, 0xb6, 0xee, 0xeb, 0xd8, 0x34, 0x00, 0xff, 0x7e, 0x2b,
	0x75, 0x97, 0x2e, 0x21, 0x5a, 0x0b, 0xae, 0x29, 0xe3, 0xa8, 0xc8, 0x21, 0x78, 0xac, 0x8c, 0x27,
	0x17, 0x93, 0xcb, 0xe8, 0xc5, 0x63, 0x65, 0x7a, 0x0e, 0xe1, 0x1d, 0x2d, 0xea, 0x52, 0x09, 0x49,
	0x08, 0x4c, 0x39, 0xdd, 0x62, 0xcf, 0xda, 0x38, 0xfd, 0x9c, 0xc0, 0xc1, 0xba, 0x61, 0xc8, 0xf5,
	0x93, 0x34, 0xa3, 0x5b, 0x12, 0x43, 0xb0, 0x47, 0xd5, 0x32, 0xc1, 0xfb, 0xc2, 0x21, 0x35, 0xfa,
	0x0f, 0xd1, 0xea, 0xd8, 0x73, 0x7a, 0x13, 0x93, 0x53, 0x08, 0x0a, 0xfa, 0xb6, 0x61, 0x0d, 0xc6,
	0xff, 0x2c, 0x3c, 0x2b, 0xe8, 0x03, 0x6b, 0x90, 0x2c, 0x21, 0x2a, 0x50, 0x69, 0x47, 0x4d, 0x2d,
	0x15, 0x1a, 0xc0, 0x92, 0x67, 0x10, 0xd6, 0xd8, 0x39, 0xce, 0x77, 0x43, 0x6a, 0xec, 0x0c, 0xb5,
	0xfa, 0x32, 0x0b, 0xfd, 0x36, 0x83, 0xdc, 0xc2, 0xe2, 0x11, 0xf5, 0x78, 0xc9, 0xb9, 0x33, 0x21,
	0x1b, 0x6e, 0x4b, 0x8e, 0x7b, 0x60, 0x5c, 0x76, 0x03, 0x47, 0xaf, 0xb2, 0xa4, 0x1a, 0xc7, 0x1d,
	0xe7, 0x99, 0x33, 0xf2, 0x47, 0xfd, 0x17, 0x20, 0x57, 0x10, 0x3d, 0x2b, 0xb1, 0x67, 0xf6, 0xee,
	0xc5, 0xd0, 0x7b, 0x70, 0x39, 0xf9, 0xdf, 0x23, 0xf6, 0x01, 0xde, 0x67, 0x36, 0xb9, 0xfe, 0x0e,
	0x00, 0x00, 0xff, 0xff, 0x10, 0x2a, 0x02, 0xfa, 0xe4, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ConfigurationClient is the client API for Configuration service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConfigurationClient interface {
	GetClientOptions(ctx context.Context, in *Backdrop, opts ...grpc.CallOption) (*ClientOptions, error)
	UpdateConfiguration(ctx context.Context, in *types.Backdrop, opts ...grpc.CallOption) (*types.Backdrop, error)
	Provision(ctx context.Context, in *Container, opts ...grpc.CallOption) (*Empty, error)
}

type configurationClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigurationClient(cc grpc.ClientConnInterface) ConfigurationClient {
	return &configurationClient{cc}
}

func (c *configurationClient) GetClientOptions(ctx context.Context, in *Backdrop, opts ...grpc.CallOption) (*ClientOptions, error) {
	out := new(ClientOptions)
	err := c.cc.Invoke(ctx, "/proto.Configuration/GetClientOptions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configurationClient) UpdateConfiguration(ctx context.Context, in *types.Backdrop, opts ...grpc.CallOption) (*types.Backdrop, error) {
	out := new(types.Backdrop)
	err := c.cc.Invoke(ctx, "/proto.Configuration/UpdateConfiguration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configurationClient) Provision(ctx context.Context, in *Container, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.Configuration/Provision", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigurationServer is the server API for Configuration service.
type ConfigurationServer interface {
	GetClientOptions(context.Context, *Backdrop) (*ClientOptions, error)
	UpdateConfiguration(context.Context, *types.Backdrop) (*types.Backdrop, error)
	Provision(context.Context, *Container) (*Empty, error)
}

// UnimplementedConfigurationServer can be embedded to have forward compatible implementations.
type UnimplementedConfigurationServer struct {
}

func (*UnimplementedConfigurationServer) GetClientOptions(ctx context.Context, req *Backdrop) (*ClientOptions, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClientOptions not implemented")
}
func (*UnimplementedConfigurationServer) UpdateConfiguration(ctx context.Context, req *types.Backdrop) (*types.Backdrop, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConfiguration not implemented")
}
func (*UnimplementedConfigurationServer) Provision(ctx context.Context, req *Container) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Provision not implemented")
}

func RegisterConfigurationServer(s *grpc.Server, srv ConfigurationServer) {
	s.RegisterService(&_Configuration_serviceDesc, srv)
}

func _Configuration_GetClientOptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Backdrop)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigurationServer).GetClientOptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Configuration/GetClientOptions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigurationServer).GetClientOptions(ctx, req.(*Backdrop))
	}
	return interceptor(ctx, in, info, handler)
}

func _Configuration_UpdateConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.Backdrop)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigurationServer).UpdateConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Configuration/UpdateConfiguration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigurationServer).UpdateConfiguration(ctx, req.(*types.Backdrop))
	}
	return interceptor(ctx, in, info, handler)
}

func _Configuration_Provision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Container)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigurationServer).Provision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Configuration/Provision",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigurationServer).Provision(ctx, req.(*Container))
	}
	return interceptor(ctx, in, info, handler)
}

var _Configuration_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Configuration",
	HandlerType: (*ConfigurationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClientOptions",
			Handler:    _Configuration_GetClientOptions_Handler,
		},
		{
			MethodName: "UpdateConfiguration",
			Handler:    _Configuration_UpdateConfiguration_Handler,
		},
		{
			MethodName: "Provision",
			Handler:    _Configuration_Provision_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/plugin/configuration/proto/configuration.proto",
}
