edition = "2023";

package wabenet.dodo.plugin.v1alpha2;

message PluginID {
  string type = 1;
  string name = 2;
}

message PluginMetadata {
  PluginID id= 1;
  repeated PluginID dependencies = 2;
  map<string, string> labels = 3;
}

message PluginConfig {
  map<string, string> config = 1;
}

message InitialStreamInput {
  string id = 1;
}

message InputData {
  bytes data = 1;
}

message OutputData {
  enum Channel {
    CHANNEL_UNSPECIFIED = 0;
    CHANNEL_STDOUT = 1;
    CHANNEL_STDERR = 2;
  }

  Channel channel = 1;
  bytes data = 2;
}

