// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: wabenet/dodo/runtime/v1alpha2/runtime.proto

package runtimev1alpha2

import (
	v1alpha2 "github.com/wabenet/dodo-core/internal/gen-proto/wabenet/dodo/plugin/v1alpha2"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateContainerResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ContainerId *string                `protobuf:"bytes,1,opt,name=container_id,json=containerId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateContainerResponse) Reset() {
	*x = CreateContainerResponse{}
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContainerResponse) ProtoMessage() {}

func (x *CreateContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateContainerResponse) GetContainerId() string {
	if x != nil {
		if x.xxx_hidden_ContainerId != nil {
			return *x.xxx_hidden_ContainerId
		}
		return ""
	}
	return ""
}

func (x *CreateContainerResponse) SetContainerId(v string) {
	x.xxx_hidden_ContainerId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *CreateContainerResponse) HasContainerId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CreateContainerResponse) ClearContainerId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ContainerId = nil
}

type CreateContainerResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ContainerId *string
}

func (b0 CreateContainerResponse_builder) Build() *CreateContainerResponse {
	m0 := &CreateContainerResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ContainerId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_ContainerId = b.ContainerId
	}
	return m0
}

type GetImageRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ImageSpec   *string                `protobuf:"bytes,1,opt,name=image_spec,json=imageSpec"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetImageRequest) Reset() {
	*x = GetImageRequest{}
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageRequest) ProtoMessage() {}

func (x *GetImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetImageRequest) GetImageSpec() string {
	if x != nil {
		if x.xxx_hidden_ImageSpec != nil {
			return *x.xxx_hidden_ImageSpec
		}
		return ""
	}
	return ""
}

func (x *GetImageRequest) SetImageSpec(v string) {
	x.xxx_hidden_ImageSpec = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetImageRequest) HasImageSpec() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetImageRequest) ClearImageSpec() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ImageSpec = nil
}

type GetImageRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ImageSpec *string
}

func (b0 GetImageRequest_builder) Build() *GetImageRequest {
	m0 := &GetImageRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ImageSpec != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_ImageSpec = b.ImageSpec
	}
	return m0
}

type CreateContainerRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Config *ContainerConfig       `protobuf:"bytes,1,opt,name=config"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateContainerRequest) Reset() {
	*x = CreateContainerRequest{}
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContainerRequest) ProtoMessage() {}

func (x *CreateContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateContainerRequest) GetConfig() *ContainerConfig {
	if x != nil {
		return x.xxx_hidden_Config
	}
	return nil
}

func (x *CreateContainerRequest) SetConfig(v *ContainerConfig) {
	x.xxx_hidden_Config = v
}

func (x *CreateContainerRequest) HasConfig() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Config != nil
}

func (x *CreateContainerRequest) ClearConfig() {
	x.xxx_hidden_Config = nil
}

type CreateContainerRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Config *ContainerConfig
}

func (b0 CreateContainerRequest_builder) Build() *CreateContainerRequest {
	m0 := &CreateContainerRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Config = b.Config
	return m0
}

type DeleteContainerRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ContainerId *string                `protobuf:"bytes,1,opt,name=container_id,json=containerId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DeleteContainerRequest) Reset() {
	*x = DeleteContainerRequest{}
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContainerRequest) ProtoMessage() {}

func (x *DeleteContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteContainerRequest) GetContainerId() string {
	if x != nil {
		if x.xxx_hidden_ContainerId != nil {
			return *x.xxx_hidden_ContainerId
		}
		return ""
	}
	return ""
}

func (x *DeleteContainerRequest) SetContainerId(v string) {
	x.xxx_hidden_ContainerId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *DeleteContainerRequest) HasContainerId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DeleteContainerRequest) ClearContainerId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ContainerId = nil
}

type DeleteContainerRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ContainerId *string
}

func (b0 DeleteContainerRequest_builder) Build() *DeleteContainerRequest {
	m0 := &DeleteContainerRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ContainerId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_ContainerId = b.ContainerId
	}
	return m0
}

type StartContainerRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ContainerId *string                `protobuf:"bytes,1,opt,name=container_id,json=containerId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StartContainerRequest) Reset() {
	*x = StartContainerRequest{}
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartContainerRequest) ProtoMessage() {}

func (x *StartContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StartContainerRequest) GetContainerId() string {
	if x != nil {
		if x.xxx_hidden_ContainerId != nil {
			return *x.xxx_hidden_ContainerId
		}
		return ""
	}
	return ""
}

func (x *StartContainerRequest) SetContainerId(v string) {
	x.xxx_hidden_ContainerId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *StartContainerRequest) HasContainerId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *StartContainerRequest) ClearContainerId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ContainerId = nil
}

type StartContainerRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ContainerId *string
}

func (b0 StartContainerRequest_builder) Build() *StartContainerRequest {
	m0 := &StartContainerRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ContainerId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_ContainerId = b.ContainerId
	}
	return m0
}

type ResizeContainerRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ContainerId *string                `protobuf:"bytes,1,opt,name=container_id,json=containerId"`
	xxx_hidden_Height      uint32                 `protobuf:"varint,2,opt,name=height"`
	xxx_hidden_Width       uint32                 `protobuf:"varint,3,opt,name=width"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ResizeContainerRequest) Reset() {
	*x = ResizeContainerRequest{}
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeContainerRequest) ProtoMessage() {}

func (x *ResizeContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ResizeContainerRequest) GetContainerId() string {
	if x != nil {
		if x.xxx_hidden_ContainerId != nil {
			return *x.xxx_hidden_ContainerId
		}
		return ""
	}
	return ""
}

func (x *ResizeContainerRequest) GetHeight() uint32 {
	if x != nil {
		return x.xxx_hidden_Height
	}
	return 0
}

func (x *ResizeContainerRequest) GetWidth() uint32 {
	if x != nil {
		return x.xxx_hidden_Width
	}
	return 0
}

func (x *ResizeContainerRequest) SetContainerId(v string) {
	x.xxx_hidden_ContainerId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *ResizeContainerRequest) SetHeight(v uint32) {
	x.xxx_hidden_Height = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *ResizeContainerRequest) SetWidth(v uint32) {
	x.xxx_hidden_Width = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *ResizeContainerRequest) HasContainerId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ResizeContainerRequest) HasHeight() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ResizeContainerRequest) HasWidth() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ResizeContainerRequest) ClearContainerId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ContainerId = nil
}

func (x *ResizeContainerRequest) ClearHeight() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Height = 0
}

func (x *ResizeContainerRequest) ClearWidth() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Width = 0
}

type ResizeContainerRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ContainerId *string
	Height      *uint32
	Width       *uint32
}

func (b0 ResizeContainerRequest_builder) Build() *ResizeContainerRequest {
	m0 := &ResizeContainerRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ContainerId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_ContainerId = b.ContainerId
	}
	if b.Height != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Height = *b.Height
	}
	if b.Width != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Width = *b.Width
	}
	return m0
}

type StreamContainerRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ContainerId *string                `protobuf:"bytes,1,opt,name=container_id,json=containerId"`
	xxx_hidden_Height      uint32                 `protobuf:"varint,2,opt,name=height"`
	xxx_hidden_Width       uint32                 `protobuf:"varint,3,opt,name=width"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StreamContainerRequest) Reset() {
	*x = StreamContainerRequest{}
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamContainerRequest) ProtoMessage() {}

func (x *StreamContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StreamContainerRequest) GetContainerId() string {
	if x != nil {
		if x.xxx_hidden_ContainerId != nil {
			return *x.xxx_hidden_ContainerId
		}
		return ""
	}
	return ""
}

func (x *StreamContainerRequest) GetHeight() uint32 {
	if x != nil {
		return x.xxx_hidden_Height
	}
	return 0
}

func (x *StreamContainerRequest) GetWidth() uint32 {
	if x != nil {
		return x.xxx_hidden_Width
	}
	return 0
}

func (x *StreamContainerRequest) SetContainerId(v string) {
	x.xxx_hidden_ContainerId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *StreamContainerRequest) SetHeight(v uint32) {
	x.xxx_hidden_Height = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *StreamContainerRequest) SetWidth(v uint32) {
	x.xxx_hidden_Width = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *StreamContainerRequest) HasContainerId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *StreamContainerRequest) HasHeight() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *StreamContainerRequest) HasWidth() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *StreamContainerRequest) ClearContainerId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ContainerId = nil
}

func (x *StreamContainerRequest) ClearHeight() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Height = 0
}

func (x *StreamContainerRequest) ClearWidth() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Width = 0
}

type StreamContainerRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ContainerId *string
	Height      *uint32
	Width       *uint32
}

func (b0 StreamContainerRequest_builder) Build() *StreamContainerRequest {
	m0 := &StreamContainerRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ContainerId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_ContainerId = b.ContainerId
	}
	if b.Height != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Height = *b.Height
	}
	if b.Width != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Width = *b.Width
	}
	return m0
}

type KillContainerRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ContainerId *string                `protobuf:"bytes,1,opt,name=container_id,json=containerId"`
	xxx_hidden_Signal      *string                `protobuf:"bytes,2,opt,name=signal"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *KillContainerRequest) Reset() {
	*x = KillContainerRequest{}
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillContainerRequest) ProtoMessage() {}

func (x *KillContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *KillContainerRequest) GetContainerId() string {
	if x != nil {
		if x.xxx_hidden_ContainerId != nil {
			return *x.xxx_hidden_ContainerId
		}
		return ""
	}
	return ""
}

func (x *KillContainerRequest) GetSignal() string {
	if x != nil {
		if x.xxx_hidden_Signal != nil {
			return *x.xxx_hidden_Signal
		}
		return ""
	}
	return ""
}

func (x *KillContainerRequest) SetContainerId(v string) {
	x.xxx_hidden_ContainerId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *KillContainerRequest) SetSignal(v string) {
	x.xxx_hidden_Signal = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *KillContainerRequest) HasContainerId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *KillContainerRequest) HasSignal() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *KillContainerRequest) ClearContainerId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ContainerId = nil
}

func (x *KillContainerRequest) ClearSignal() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Signal = nil
}

type KillContainerRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ContainerId *string
	Signal      *string
}

func (b0 KillContainerRequest_builder) Build() *KillContainerRequest {
	m0 := &KillContainerRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ContainerId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_ContainerId = b.ContainerId
	}
	if b.Signal != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Signal = b.Signal
	}
	return m0
}

type StreamContainerResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ExitCode    int64                  `protobuf:"varint,1,opt,name=exitCode"`
	xxx_hidden_Message     *string                `protobuf:"bytes,2,opt,name=message"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StreamContainerResponse) Reset() {
	*x = StreamContainerResponse{}
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamContainerResponse) ProtoMessage() {}

func (x *StreamContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StreamContainerResponse) GetExitCode() int64 {
	if x != nil {
		return x.xxx_hidden_ExitCode
	}
	return 0
}

func (x *StreamContainerResponse) GetMessage() string {
	if x != nil {
		if x.xxx_hidden_Message != nil {
			return *x.xxx_hidden_Message
		}
		return ""
	}
	return ""
}

func (x *StreamContainerResponse) SetExitCode(v int64) {
	x.xxx_hidden_ExitCode = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *StreamContainerResponse) SetMessage(v string) {
	x.xxx_hidden_Message = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *StreamContainerResponse) HasExitCode() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *StreamContainerResponse) HasMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *StreamContainerResponse) ClearExitCode() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ExitCode = 0
}

func (x *StreamContainerResponse) ClearMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Message = nil
}

type StreamContainerResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ExitCode *int64
	Message  *string
}

func (b0 StreamContainerResponse_builder) Build() *StreamContainerResponse {
	m0 := &StreamContainerResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ExitCode != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_ExitCode = *b.ExitCode
	}
	if b.Message != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Message = b.Message
	}
	return m0
}

type CreateVolumeRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateVolumeRequest) Reset() {
	*x = CreateVolumeRequest{}
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVolumeRequest) ProtoMessage() {}

func (x *CreateVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateVolumeRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *CreateVolumeRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *CreateVolumeRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CreateVolumeRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

type CreateVolumeRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name *string
}

func (b0 CreateVolumeRequest_builder) Build() *CreateVolumeRequest {
	m0 := &CreateVolumeRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Name = b.Name
	}
	return m0
}

type DeleteVolumeRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DeleteVolumeRequest) Reset() {
	*x = DeleteVolumeRequest{}
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVolumeRequest) ProtoMessage() {}

func (x *DeleteVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteVolumeRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *DeleteVolumeRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *DeleteVolumeRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DeleteVolumeRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

type DeleteVolumeRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name *string
}

func (b0 DeleteVolumeRequest_builder) Build() *DeleteVolumeRequest {
	m0 := &DeleteVolumeRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Name = b.Name
	}
	return m0
}

type WriteFileRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ContainerId *string                `protobuf:"bytes,1,opt,name=container_id,json=containerId"`
	xxx_hidden_FilePath    *string                `protobuf:"bytes,2,opt,name=file_path,json=filePath"`
	xxx_hidden_Contents    *string                `protobuf:"bytes,3,opt,name=contents"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *WriteFileRequest) Reset() {
	*x = WriteFileRequest{}
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileRequest) ProtoMessage() {}

func (x *WriteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *WriteFileRequest) GetContainerId() string {
	if x != nil {
		if x.xxx_hidden_ContainerId != nil {
			return *x.xxx_hidden_ContainerId
		}
		return ""
	}
	return ""
}

func (x *WriteFileRequest) GetFilePath() string {
	if x != nil {
		if x.xxx_hidden_FilePath != nil {
			return *x.xxx_hidden_FilePath
		}
		return ""
	}
	return ""
}

func (x *WriteFileRequest) GetContents() string {
	if x != nil {
		if x.xxx_hidden_Contents != nil {
			return *x.xxx_hidden_Contents
		}
		return ""
	}
	return ""
}

func (x *WriteFileRequest) SetContainerId(v string) {
	x.xxx_hidden_ContainerId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *WriteFileRequest) SetFilePath(v string) {
	x.xxx_hidden_FilePath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *WriteFileRequest) SetContents(v string) {
	x.xxx_hidden_Contents = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *WriteFileRequest) HasContainerId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *WriteFileRequest) HasFilePath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *WriteFileRequest) HasContents() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *WriteFileRequest) ClearContainerId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ContainerId = nil
}

func (x *WriteFileRequest) ClearFilePath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_FilePath = nil
}

func (x *WriteFileRequest) ClearContents() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Contents = nil
}

type WriteFileRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ContainerId *string
	FilePath    *string
	Contents    *string
}

func (b0 WriteFileRequest_builder) Build() *WriteFileRequest {
	m0 := &WriteFileRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ContainerId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_ContainerId = b.ContainerId
	}
	if b.FilePath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_FilePath = b.FilePath
	}
	if b.Contents != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Contents = b.Contents
	}
	return m0
}

type GetImageResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ImageId     *string                `protobuf:"bytes,1,opt,name=image_id,json=imageId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetImageResponse) Reset() {
	*x = GetImageResponse{}
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageResponse) ProtoMessage() {}

func (x *GetImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetImageResponse) GetImageId() string {
	if x != nil {
		if x.xxx_hidden_ImageId != nil {
			return *x.xxx_hidden_ImageId
		}
		return ""
	}
	return ""
}

func (x *GetImageResponse) SetImageId(v string) {
	x.xxx_hidden_ImageId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetImageResponse) HasImageId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetImageResponse) ClearImageId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ImageId = nil
}

type GetImageResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ImageId *string
}

func (b0 GetImageResponse_builder) Build() *GetImageResponse {
	m0 := &GetImageResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ImageId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_ImageId = b.ImageId
	}
	return m0
}

type ContainerConfig struct {
	state                   protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_Name         *string                 `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Image        *string                 `protobuf:"bytes,2,opt,name=image"`
	xxx_hidden_Process      *Process                `protobuf:"bytes,3,opt,name=process"`
	xxx_hidden_Terminal     *TerminalConfig         `protobuf:"bytes,4,opt,name=terminal"`
	xxx_hidden_Environment  *[]*EnvironmentVariable `protobuf:"bytes,5,rep,name=environment"`
	xxx_hidden_Ports        *[]*PortBinding         `protobuf:"bytes,6,rep,name=ports"`
	xxx_hidden_Mounts       *[]*Mount               `protobuf:"bytes,7,rep,name=mounts"`
	xxx_hidden_Capabilities []string                `protobuf:"bytes,8,rep,name=capabilities"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ContainerConfig) Reset() {
	*x = ContainerConfig{}
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerConfig) ProtoMessage() {}

func (x *ContainerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ContainerConfig) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *ContainerConfig) GetImage() string {
	if x != nil {
		if x.xxx_hidden_Image != nil {
			return *x.xxx_hidden_Image
		}
		return ""
	}
	return ""
}

func (x *ContainerConfig) GetProcess() *Process {
	if x != nil {
		return x.xxx_hidden_Process
	}
	return nil
}

func (x *ContainerConfig) GetTerminal() *TerminalConfig {
	if x != nil {
		return x.xxx_hidden_Terminal
	}
	return nil
}

func (x *ContainerConfig) GetEnvironment() []*EnvironmentVariable {
	if x != nil {
		if x.xxx_hidden_Environment != nil {
			return *x.xxx_hidden_Environment
		}
	}
	return nil
}

func (x *ContainerConfig) GetPorts() []*PortBinding {
	if x != nil {
		if x.xxx_hidden_Ports != nil {
			return *x.xxx_hidden_Ports
		}
	}
	return nil
}

func (x *ContainerConfig) GetMounts() []*Mount {
	if x != nil {
		if x.xxx_hidden_Mounts != nil {
			return *x.xxx_hidden_Mounts
		}
	}
	return nil
}

func (x *ContainerConfig) GetCapabilities() []string {
	if x != nil {
		return x.xxx_hidden_Capabilities
	}
	return nil
}

func (x *ContainerConfig) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 8)
}

func (x *ContainerConfig) SetImage(v string) {
	x.xxx_hidden_Image = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 8)
}

func (x *ContainerConfig) SetProcess(v *Process) {
	x.xxx_hidden_Process = v
}

func (x *ContainerConfig) SetTerminal(v *TerminalConfig) {
	x.xxx_hidden_Terminal = v
}

func (x *ContainerConfig) SetEnvironment(v []*EnvironmentVariable) {
	x.xxx_hidden_Environment = &v
}

func (x *ContainerConfig) SetPorts(v []*PortBinding) {
	x.xxx_hidden_Ports = &v
}

func (x *ContainerConfig) SetMounts(v []*Mount) {
	x.xxx_hidden_Mounts = &v
}

func (x *ContainerConfig) SetCapabilities(v []string) {
	x.xxx_hidden_Capabilities = v
}

func (x *ContainerConfig) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ContainerConfig) HasImage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ContainerConfig) HasProcess() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Process != nil
}

func (x *ContainerConfig) HasTerminal() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Terminal != nil
}

func (x *ContainerConfig) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *ContainerConfig) ClearImage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Image = nil
}

func (x *ContainerConfig) ClearProcess() {
	x.xxx_hidden_Process = nil
}

func (x *ContainerConfig) ClearTerminal() {
	x.xxx_hidden_Terminal = nil
}

type ContainerConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name         *string
	Image        *string
	Process      *Process
	Terminal     *TerminalConfig
	Environment  []*EnvironmentVariable
	Ports        []*PortBinding
	Mounts       []*Mount
	Capabilities []string
}

func (b0 ContainerConfig_builder) Build() *ContainerConfig {
	m0 := &ContainerConfig{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 8)
		x.xxx_hidden_Name = b.Name
	}
	if b.Image != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 8)
		x.xxx_hidden_Image = b.Image
	}
	x.xxx_hidden_Process = b.Process
	x.xxx_hidden_Terminal = b.Terminal
	x.xxx_hidden_Environment = &b.Environment
	x.xxx_hidden_Ports = &b.Ports
	x.xxx_hidden_Mounts = &b.Mounts
	x.xxx_hidden_Capabilities = b.Capabilities
	return m0
}

type Process struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_User        *string                `protobuf:"bytes,1,opt,name=user"`
	xxx_hidden_WorkingDir  *string                `protobuf:"bytes,2,opt,name=working_dir,json=workingDir"`
	xxx_hidden_Entrypoint  []string               `protobuf:"bytes,3,rep,name=entrypoint"`
	xxx_hidden_Command     []string               `protobuf:"bytes,4,rep,name=command"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Process) Reset() {
	*x = Process{}
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Process) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process) ProtoMessage() {}

func (x *Process) ProtoReflect() protoreflect.Message {
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Process) GetUser() string {
	if x != nil {
		if x.xxx_hidden_User != nil {
			return *x.xxx_hidden_User
		}
		return ""
	}
	return ""
}

func (x *Process) GetWorkingDir() string {
	if x != nil {
		if x.xxx_hidden_WorkingDir != nil {
			return *x.xxx_hidden_WorkingDir
		}
		return ""
	}
	return ""
}

func (x *Process) GetEntrypoint() []string {
	if x != nil {
		return x.xxx_hidden_Entrypoint
	}
	return nil
}

func (x *Process) GetCommand() []string {
	if x != nil {
		return x.xxx_hidden_Command
	}
	return nil
}

func (x *Process) SetUser(v string) {
	x.xxx_hidden_User = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *Process) SetWorkingDir(v string) {
	x.xxx_hidden_WorkingDir = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *Process) SetEntrypoint(v []string) {
	x.xxx_hidden_Entrypoint = v
}

func (x *Process) SetCommand(v []string) {
	x.xxx_hidden_Command = v
}

func (x *Process) HasUser() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Process) HasWorkingDir() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Process) ClearUser() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_User = nil
}

func (x *Process) ClearWorkingDir() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_WorkingDir = nil
}

type Process_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	User       *string
	WorkingDir *string
	Entrypoint []string
	Command    []string
}

func (b0 Process_builder) Build() *Process {
	m0 := &Process{}
	b, x := &b0, m0
	_, _ = b, x
	if b.User != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_User = b.User
	}
	if b.WorkingDir != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_WorkingDir = b.WorkingDir
	}
	x.xxx_hidden_Entrypoint = b.Entrypoint
	x.xxx_hidden_Command = b.Command
	return m0
}

type TerminalConfig struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Stdio         bool                   `protobuf:"varint,1,opt,name=stdio"`
	xxx_hidden_Tty           bool                   `protobuf:"varint,2,opt,name=tty"`
	xxx_hidden_ConsoleHeight int64                  `protobuf:"varint,3,opt,name=consoleHeight"`
	xxx_hidden_ConsoleWidth  int64                  `protobuf:"varint,4,opt,name=consoleWidth"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *TerminalConfig) Reset() {
	*x = TerminalConfig{}
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalConfig) ProtoMessage() {}

func (x *TerminalConfig) ProtoReflect() protoreflect.Message {
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TerminalConfig) GetStdio() bool {
	if x != nil {
		return x.xxx_hidden_Stdio
	}
	return false
}

func (x *TerminalConfig) GetTty() bool {
	if x != nil {
		return x.xxx_hidden_Tty
	}
	return false
}

func (x *TerminalConfig) GetConsoleHeight() int64 {
	if x != nil {
		return x.xxx_hidden_ConsoleHeight
	}
	return 0
}

func (x *TerminalConfig) GetConsoleWidth() int64 {
	if x != nil {
		return x.xxx_hidden_ConsoleWidth
	}
	return 0
}

func (x *TerminalConfig) SetStdio(v bool) {
	x.xxx_hidden_Stdio = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *TerminalConfig) SetTty(v bool) {
	x.xxx_hidden_Tty = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *TerminalConfig) SetConsoleHeight(v int64) {
	x.xxx_hidden_ConsoleHeight = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *TerminalConfig) SetConsoleWidth(v int64) {
	x.xxx_hidden_ConsoleWidth = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *TerminalConfig) HasStdio() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *TerminalConfig) HasTty() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *TerminalConfig) HasConsoleHeight() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *TerminalConfig) HasConsoleWidth() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *TerminalConfig) ClearStdio() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Stdio = false
}

func (x *TerminalConfig) ClearTty() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Tty = false
}

func (x *TerminalConfig) ClearConsoleHeight() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ConsoleHeight = 0
}

func (x *TerminalConfig) ClearConsoleWidth() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_ConsoleWidth = 0
}

type TerminalConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Stdio         *bool
	Tty           *bool
	ConsoleHeight *int64
	ConsoleWidth  *int64
}

func (b0 TerminalConfig_builder) Build() *TerminalConfig {
	m0 := &TerminalConfig{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Stdio != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Stdio = *b.Stdio
	}
	if b.Tty != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Tty = *b.Tty
	}
	if b.ConsoleHeight != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_ConsoleHeight = *b.ConsoleHeight
	}
	if b.ConsoleWidth != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_ConsoleWidth = *b.ConsoleWidth
	}
	return m0
}

type EnvironmentVariable struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key         *string                `protobuf:"bytes,1,opt,name=key"`
	xxx_hidden_Value       *string                `protobuf:"bytes,2,opt,name=value"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *EnvironmentVariable) Reset() {
	*x = EnvironmentVariable{}
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvironmentVariable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvironmentVariable) ProtoMessage() {}

func (x *EnvironmentVariable) ProtoReflect() protoreflect.Message {
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EnvironmentVariable) GetKey() string {
	if x != nil {
		if x.xxx_hidden_Key != nil {
			return *x.xxx_hidden_Key
		}
		return ""
	}
	return ""
}

func (x *EnvironmentVariable) GetValue() string {
	if x != nil {
		if x.xxx_hidden_Value != nil {
			return *x.xxx_hidden_Value
		}
		return ""
	}
	return ""
}

func (x *EnvironmentVariable) SetKey(v string) {
	x.xxx_hidden_Key = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *EnvironmentVariable) SetValue(v string) {
	x.xxx_hidden_Value = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *EnvironmentVariable) HasKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *EnvironmentVariable) HasValue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *EnvironmentVariable) ClearKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Key = nil
}

func (x *EnvironmentVariable) ClearValue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Value = nil
}

type EnvironmentVariable_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Key   *string
	Value *string
}

func (b0 EnvironmentVariable_builder) Build() *EnvironmentVariable {
	m0 := &EnvironmentVariable{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Key != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Key = b.Key
	}
	if b.Value != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Value = b.Value
	}
	return m0
}

type PortBinding struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_HostPort      *string                `protobuf:"bytes,1,opt,name=host_port,json=hostPort"`
	xxx_hidden_ContainerPort *string                `protobuf:"bytes,2,opt,name=container_port,json=containerPort"`
	xxx_hidden_Protocol      *string                `protobuf:"bytes,3,opt,name=protocol"`
	xxx_hidden_HostIp        *string                `protobuf:"bytes,4,opt,name=host_ip,json=hostIp"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *PortBinding) Reset() {
	*x = PortBinding{}
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortBinding) ProtoMessage() {}

func (x *PortBinding) ProtoReflect() protoreflect.Message {
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PortBinding) GetHostPort() string {
	if x != nil {
		if x.xxx_hidden_HostPort != nil {
			return *x.xxx_hidden_HostPort
		}
		return ""
	}
	return ""
}

func (x *PortBinding) GetContainerPort() string {
	if x != nil {
		if x.xxx_hidden_ContainerPort != nil {
			return *x.xxx_hidden_ContainerPort
		}
		return ""
	}
	return ""
}

func (x *PortBinding) GetProtocol() string {
	if x != nil {
		if x.xxx_hidden_Protocol != nil {
			return *x.xxx_hidden_Protocol
		}
		return ""
	}
	return ""
}

func (x *PortBinding) GetHostIp() string {
	if x != nil {
		if x.xxx_hidden_HostIp != nil {
			return *x.xxx_hidden_HostIp
		}
		return ""
	}
	return ""
}

func (x *PortBinding) SetHostPort(v string) {
	x.xxx_hidden_HostPort = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *PortBinding) SetContainerPort(v string) {
	x.xxx_hidden_ContainerPort = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *PortBinding) SetProtocol(v string) {
	x.xxx_hidden_Protocol = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *PortBinding) SetHostIp(v string) {
	x.xxx_hidden_HostIp = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *PortBinding) HasHostPort() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *PortBinding) HasContainerPort() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *PortBinding) HasProtocol() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *PortBinding) HasHostIp() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *PortBinding) ClearHostPort() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_HostPort = nil
}

func (x *PortBinding) ClearContainerPort() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ContainerPort = nil
}

func (x *PortBinding) ClearProtocol() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Protocol = nil
}

func (x *PortBinding) ClearHostIp() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_HostIp = nil
}

type PortBinding_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	HostPort      *string
	ContainerPort *string
	Protocol      *string
	HostIp        *string
}

func (b0 PortBinding_builder) Build() *PortBinding {
	m0 := &PortBinding{}
	b, x := &b0, m0
	_, _ = b, x
	if b.HostPort != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_HostPort = b.HostPort
	}
	if b.ContainerPort != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_ContainerPort = b.ContainerPort
	}
	if b.Protocol != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Protocol = b.Protocol
	}
	if b.HostIp != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_HostIp = b.HostIp
	}
	return m0
}

type Mount struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type isMount_Type           `protobuf_oneof:"type"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Mount) Reset() {
	*x = Mount{}
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mount) ProtoMessage() {}

func (x *Mount) ProtoReflect() protoreflect.Message {
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Mount) GetBind() *BindMount {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*mount_Bind); ok {
			return x.Bind
		}
	}
	return nil
}

func (x *Mount) GetVolume() *VolumeMount {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*mount_Volume); ok {
			return x.Volume
		}
	}
	return nil
}

func (x *Mount) GetTmpfs() *TmpfsMount {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*mount_Tmpfs); ok {
			return x.Tmpfs
		}
	}
	return nil
}

func (x *Mount) GetImage() *ImageMount {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*mount_Image); ok {
			return x.Image
		}
	}
	return nil
}

func (x *Mount) GetDevice() *DeviceMount {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*mount_Device); ok {
			return x.Device
		}
	}
	return nil
}

func (x *Mount) SetBind(v *BindMount) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &mount_Bind{v}
}

func (x *Mount) SetVolume(v *VolumeMount) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &mount_Volume{v}
}

func (x *Mount) SetTmpfs(v *TmpfsMount) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &mount_Tmpfs{v}
}

func (x *Mount) SetImage(v *ImageMount) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &mount_Image{v}
}

func (x *Mount) SetDevice(v *DeviceMount) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &mount_Device{v}
}

func (x *Mount) HasType() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Type != nil
}

func (x *Mount) HasBind() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*mount_Bind)
	return ok
}

func (x *Mount) HasVolume() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*mount_Volume)
	return ok
}

func (x *Mount) HasTmpfs() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*mount_Tmpfs)
	return ok
}

func (x *Mount) HasImage() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*mount_Image)
	return ok
}

func (x *Mount) HasDevice() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*mount_Device)
	return ok
}

func (x *Mount) ClearType() {
	x.xxx_hidden_Type = nil
}

func (x *Mount) ClearBind() {
	if _, ok := x.xxx_hidden_Type.(*mount_Bind); ok {
		x.xxx_hidden_Type = nil
	}
}

func (x *Mount) ClearVolume() {
	if _, ok := x.xxx_hidden_Type.(*mount_Volume); ok {
		x.xxx_hidden_Type = nil
	}
}

func (x *Mount) ClearTmpfs() {
	if _, ok := x.xxx_hidden_Type.(*mount_Tmpfs); ok {
		x.xxx_hidden_Type = nil
	}
}

func (x *Mount) ClearImage() {
	if _, ok := x.xxx_hidden_Type.(*mount_Image); ok {
		x.xxx_hidden_Type = nil
	}
}

func (x *Mount) ClearDevice() {
	if _, ok := x.xxx_hidden_Type.(*mount_Device); ok {
		x.xxx_hidden_Type = nil
	}
}

const Mount_Type_not_set_case case_Mount_Type = 0
const Mount_Bind_case case_Mount_Type = 1
const Mount_Volume_case case_Mount_Type = 2
const Mount_Tmpfs_case case_Mount_Type = 3
const Mount_Image_case case_Mount_Type = 4
const Mount_Device_case case_Mount_Type = 5

func (x *Mount) WhichType() case_Mount_Type {
	if x == nil {
		return Mount_Type_not_set_case
	}
	switch x.xxx_hidden_Type.(type) {
	case *mount_Bind:
		return Mount_Bind_case
	case *mount_Volume:
		return Mount_Volume_case
	case *mount_Tmpfs:
		return Mount_Tmpfs_case
	case *mount_Image:
		return Mount_Image_case
	case *mount_Device:
		return Mount_Device_case
	default:
		return Mount_Type_not_set_case
	}
}

type Mount_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Type:
	Bind   *BindMount
	Volume *VolumeMount
	Tmpfs  *TmpfsMount
	Image  *ImageMount
	Device *DeviceMount
	// -- end of xxx_hidden_Type
}

func (b0 Mount_builder) Build() *Mount {
	m0 := &Mount{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Bind != nil {
		x.xxx_hidden_Type = &mount_Bind{b.Bind}
	}
	if b.Volume != nil {
		x.xxx_hidden_Type = &mount_Volume{b.Volume}
	}
	if b.Tmpfs != nil {
		x.xxx_hidden_Type = &mount_Tmpfs{b.Tmpfs}
	}
	if b.Image != nil {
		x.xxx_hidden_Type = &mount_Image{b.Image}
	}
	if b.Device != nil {
		x.xxx_hidden_Type = &mount_Device{b.Device}
	}
	return m0
}

type case_Mount_Type protoreflect.FieldNumber

func (x case_Mount_Type) String() string {
	md := file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[18].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isMount_Type interface {
	isMount_Type()
}

type mount_Bind struct {
	Bind *BindMount `protobuf:"bytes,1,opt,name=bind,oneof"`
}

type mount_Volume struct {
	Volume *VolumeMount `protobuf:"bytes,2,opt,name=volume,oneof"`
}

type mount_Tmpfs struct {
	Tmpfs *TmpfsMount `protobuf:"bytes,3,opt,name=tmpfs,oneof"`
}

type mount_Image struct {
	Image *ImageMount `protobuf:"bytes,4,opt,name=image,oneof"`
}

type mount_Device struct {
	Device *DeviceMount `protobuf:"bytes,5,opt,name=device,oneof"`
}

func (*mount_Bind) isMount_Type() {}

func (*mount_Volume) isMount_Type() {}

func (*mount_Tmpfs) isMount_Type() {}

func (*mount_Image) isMount_Type() {}

func (*mount_Device) isMount_Type() {}

type BindMount struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_HostPath      *string                `protobuf:"bytes,1,opt,name=host_path,json=hostPath"`
	xxx_hidden_ContainerPath *string                `protobuf:"bytes,2,opt,name=container_path,json=containerPath"`
	xxx_hidden_Readonly      bool                   `protobuf:"varint,3,opt,name=readonly"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *BindMount) Reset() {
	*x = BindMount{}
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindMount) ProtoMessage() {}

func (x *BindMount) ProtoReflect() protoreflect.Message {
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BindMount) GetHostPath() string {
	if x != nil {
		if x.xxx_hidden_HostPath != nil {
			return *x.xxx_hidden_HostPath
		}
		return ""
	}
	return ""
}

func (x *BindMount) GetContainerPath() string {
	if x != nil {
		if x.xxx_hidden_ContainerPath != nil {
			return *x.xxx_hidden_ContainerPath
		}
		return ""
	}
	return ""
}

func (x *BindMount) GetReadonly() bool {
	if x != nil {
		return x.xxx_hidden_Readonly
	}
	return false
}

func (x *BindMount) SetHostPath(v string) {
	x.xxx_hidden_HostPath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *BindMount) SetContainerPath(v string) {
	x.xxx_hidden_ContainerPath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *BindMount) SetReadonly(v bool) {
	x.xxx_hidden_Readonly = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *BindMount) HasHostPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *BindMount) HasContainerPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *BindMount) HasReadonly() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *BindMount) ClearHostPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_HostPath = nil
}

func (x *BindMount) ClearContainerPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ContainerPath = nil
}

func (x *BindMount) ClearReadonly() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Readonly = false
}

type BindMount_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	HostPath      *string
	ContainerPath *string
	Readonly      *bool
}

func (b0 BindMount_builder) Build() *BindMount {
	m0 := &BindMount{}
	b, x := &b0, m0
	_, _ = b, x
	if b.HostPath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_HostPath = b.HostPath
	}
	if b.ContainerPath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_ContainerPath = b.ContainerPath
	}
	if b.Readonly != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Readonly = *b.Readonly
	}
	return m0
}

type VolumeMount struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_VolumeName    *string                `protobuf:"bytes,1,opt,name=volume_name,json=volumeName"`
	xxx_hidden_ContainerPath *string                `protobuf:"bytes,2,opt,name=container_path,json=containerPath"`
	xxx_hidden_Subpath       *string                `protobuf:"bytes,3,opt,name=subpath"`
	xxx_hidden_Readonly      bool                   `protobuf:"varint,4,opt,name=readonly"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *VolumeMount) Reset() {
	*x = VolumeMount{}
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeMount) ProtoMessage() {}

func (x *VolumeMount) ProtoReflect() protoreflect.Message {
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *VolumeMount) GetVolumeName() string {
	if x != nil {
		if x.xxx_hidden_VolumeName != nil {
			return *x.xxx_hidden_VolumeName
		}
		return ""
	}
	return ""
}

func (x *VolumeMount) GetContainerPath() string {
	if x != nil {
		if x.xxx_hidden_ContainerPath != nil {
			return *x.xxx_hidden_ContainerPath
		}
		return ""
	}
	return ""
}

func (x *VolumeMount) GetSubpath() string {
	if x != nil {
		if x.xxx_hidden_Subpath != nil {
			return *x.xxx_hidden_Subpath
		}
		return ""
	}
	return ""
}

func (x *VolumeMount) GetReadonly() bool {
	if x != nil {
		return x.xxx_hidden_Readonly
	}
	return false
}

func (x *VolumeMount) SetVolumeName(v string) {
	x.xxx_hidden_VolumeName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *VolumeMount) SetContainerPath(v string) {
	x.xxx_hidden_ContainerPath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *VolumeMount) SetSubpath(v string) {
	x.xxx_hidden_Subpath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *VolumeMount) SetReadonly(v bool) {
	x.xxx_hidden_Readonly = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *VolumeMount) HasVolumeName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *VolumeMount) HasContainerPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *VolumeMount) HasSubpath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *VolumeMount) HasReadonly() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *VolumeMount) ClearVolumeName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_VolumeName = nil
}

func (x *VolumeMount) ClearContainerPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ContainerPath = nil
}

func (x *VolumeMount) ClearSubpath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Subpath = nil
}

func (x *VolumeMount) ClearReadonly() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Readonly = false
}

type VolumeMount_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	VolumeName    *string
	ContainerPath *string
	Subpath       *string
	Readonly      *bool
}

func (b0 VolumeMount_builder) Build() *VolumeMount {
	m0 := &VolumeMount{}
	b, x := &b0, m0
	_, _ = b, x
	if b.VolumeName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_VolumeName = b.VolumeName
	}
	if b.ContainerPath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_ContainerPath = b.ContainerPath
	}
	if b.Subpath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Subpath = b.Subpath
	}
	if b.Readonly != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Readonly = *b.Readonly
	}
	return m0
}

type TmpfsMount struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ContainerPath *string                `protobuf:"bytes,1,opt,name=container_path,json=containerPath"`
	xxx_hidden_Size          int64                  `protobuf:"varint,2,opt,name=size"`
	xxx_hidden_Mode          *string                `protobuf:"bytes,3,opt,name=mode"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *TmpfsMount) Reset() {
	*x = TmpfsMount{}
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TmpfsMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TmpfsMount) ProtoMessage() {}

func (x *TmpfsMount) ProtoReflect() protoreflect.Message {
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TmpfsMount) GetContainerPath() string {
	if x != nil {
		if x.xxx_hidden_ContainerPath != nil {
			return *x.xxx_hidden_ContainerPath
		}
		return ""
	}
	return ""
}

func (x *TmpfsMount) GetSize() int64 {
	if x != nil {
		return x.xxx_hidden_Size
	}
	return 0
}

func (x *TmpfsMount) GetMode() string {
	if x != nil {
		if x.xxx_hidden_Mode != nil {
			return *x.xxx_hidden_Mode
		}
		return ""
	}
	return ""
}

func (x *TmpfsMount) SetContainerPath(v string) {
	x.xxx_hidden_ContainerPath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *TmpfsMount) SetSize(v int64) {
	x.xxx_hidden_Size = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *TmpfsMount) SetMode(v string) {
	x.xxx_hidden_Mode = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *TmpfsMount) HasContainerPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *TmpfsMount) HasSize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *TmpfsMount) HasMode() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *TmpfsMount) ClearContainerPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ContainerPath = nil
}

func (x *TmpfsMount) ClearSize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Size = 0
}

func (x *TmpfsMount) ClearMode() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Mode = nil
}

type TmpfsMount_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ContainerPath *string
	Size          *int64
	Mode          *string
}

func (b0 TmpfsMount_builder) Build() *TmpfsMount {
	m0 := &TmpfsMount{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ContainerPath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_ContainerPath = b.ContainerPath
	}
	if b.Size != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Size = *b.Size
	}
	if b.Mode != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Mode = b.Mode
	}
	return m0
}

type ImageMount struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Image         *string                `protobuf:"bytes,1,opt,name=image"`
	xxx_hidden_ContainerPath *string                `protobuf:"bytes,2,opt,name=container_path,json=containerPath"`
	xxx_hidden_Subpath       *string                `protobuf:"bytes,3,opt,name=subpath"`
	xxx_hidden_Readonly      bool                   `protobuf:"varint,4,opt,name=readonly"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ImageMount) Reset() {
	*x = ImageMount{}
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageMount) ProtoMessage() {}

func (x *ImageMount) ProtoReflect() protoreflect.Message {
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ImageMount) GetImage() string {
	if x != nil {
		if x.xxx_hidden_Image != nil {
			return *x.xxx_hidden_Image
		}
		return ""
	}
	return ""
}

func (x *ImageMount) GetContainerPath() string {
	if x != nil {
		if x.xxx_hidden_ContainerPath != nil {
			return *x.xxx_hidden_ContainerPath
		}
		return ""
	}
	return ""
}

func (x *ImageMount) GetSubpath() string {
	if x != nil {
		if x.xxx_hidden_Subpath != nil {
			return *x.xxx_hidden_Subpath
		}
		return ""
	}
	return ""
}

func (x *ImageMount) GetReadonly() bool {
	if x != nil {
		return x.xxx_hidden_Readonly
	}
	return false
}

func (x *ImageMount) SetImage(v string) {
	x.xxx_hidden_Image = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *ImageMount) SetContainerPath(v string) {
	x.xxx_hidden_ContainerPath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *ImageMount) SetSubpath(v string) {
	x.xxx_hidden_Subpath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *ImageMount) SetReadonly(v bool) {
	x.xxx_hidden_Readonly = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *ImageMount) HasImage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ImageMount) HasContainerPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ImageMount) HasSubpath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ImageMount) HasReadonly() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ImageMount) ClearImage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Image = nil
}

func (x *ImageMount) ClearContainerPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ContainerPath = nil
}

func (x *ImageMount) ClearSubpath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Subpath = nil
}

func (x *ImageMount) ClearReadonly() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Readonly = false
}

type ImageMount_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Image         *string
	ContainerPath *string
	Subpath       *string
	Readonly      *bool
}

func (b0 ImageMount_builder) Build() *ImageMount {
	m0 := &ImageMount{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Image != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Image = b.Image
	}
	if b.ContainerPath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_ContainerPath = b.ContainerPath
	}
	if b.Subpath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Subpath = b.Subpath
	}
	if b.Readonly != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Readonly = *b.Readonly
	}
	return m0
}

type DeviceMount struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_CgroupRule    *string                `protobuf:"bytes,1,opt,name=cgroup_rule,json=cgroupRule"`
	xxx_hidden_HostPath      *string                `protobuf:"bytes,2,opt,name=host_path,json=hostPath"`
	xxx_hidden_ContainerPath *string                `protobuf:"bytes,3,opt,name=container_path,json=containerPath"`
	xxx_hidden_Permissions   *string                `protobuf:"bytes,4,opt,name=permissions"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *DeviceMount) Reset() {
	*x = DeviceMount{}
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceMount) ProtoMessage() {}

func (x *DeviceMount) ProtoReflect() protoreflect.Message {
	mi := &file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeviceMount) GetCgroupRule() string {
	if x != nil {
		if x.xxx_hidden_CgroupRule != nil {
			return *x.xxx_hidden_CgroupRule
		}
		return ""
	}
	return ""
}

func (x *DeviceMount) GetHostPath() string {
	if x != nil {
		if x.xxx_hidden_HostPath != nil {
			return *x.xxx_hidden_HostPath
		}
		return ""
	}
	return ""
}

func (x *DeviceMount) GetContainerPath() string {
	if x != nil {
		if x.xxx_hidden_ContainerPath != nil {
			return *x.xxx_hidden_ContainerPath
		}
		return ""
	}
	return ""
}

func (x *DeviceMount) GetPermissions() string {
	if x != nil {
		if x.xxx_hidden_Permissions != nil {
			return *x.xxx_hidden_Permissions
		}
		return ""
	}
	return ""
}

func (x *DeviceMount) SetCgroupRule(v string) {
	x.xxx_hidden_CgroupRule = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *DeviceMount) SetHostPath(v string) {
	x.xxx_hidden_HostPath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *DeviceMount) SetContainerPath(v string) {
	x.xxx_hidden_ContainerPath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *DeviceMount) SetPermissions(v string) {
	x.xxx_hidden_Permissions = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *DeviceMount) HasCgroupRule() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DeviceMount) HasHostPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DeviceMount) HasContainerPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *DeviceMount) HasPermissions() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *DeviceMount) ClearCgroupRule() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_CgroupRule = nil
}

func (x *DeviceMount) ClearHostPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_HostPath = nil
}

func (x *DeviceMount) ClearContainerPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ContainerPath = nil
}

func (x *DeviceMount) ClearPermissions() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Permissions = nil
}

type DeviceMount_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	CgroupRule    *string
	HostPath      *string
	ContainerPath *string
	Permissions   *string
}

func (b0 DeviceMount_builder) Build() *DeviceMount {
	m0 := &DeviceMount{}
	b, x := &b0, m0
	_, _ = b, x
	if b.CgroupRule != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_CgroupRule = b.CgroupRule
	}
	if b.HostPath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_HostPath = b.HostPath
	}
	if b.ContainerPath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_ContainerPath = b.ContainerPath
	}
	if b.Permissions != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Permissions = b.Permissions
	}
	return m0
}

var File_wabenet_dodo_runtime_v1alpha2_runtime_proto protoreflect.FileDescriptor

const file_wabenet_dodo_runtime_v1alpha2_runtime_proto_rawDesc = "" +
	"\n" +
	"+wabenet/dodo/runtime/v1alpha2/runtime.proto\x12\x1dwabenet.dodo.runtime.v1alpha2\x1a\x1bgoogle/protobuf/empty.proto\x1a)wabenet/dodo/plugin/v1alpha2/plugin.proto\"<\n" +
	"\x17CreateContainerResponse\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\"0\n" +
	"\x0fGetImageRequest\x12\x1d\n" +
	"\n" +
	"image_spec\x18\x01 \x01(\tR\timageSpec\"`\n" +
	"\x16CreateContainerRequest\x12F\n" +
	"\x06config\x18\x01 \x01(\v2..wabenet.dodo.runtime.v1alpha2.ContainerConfigR\x06config\";\n" +
	"\x16DeleteContainerRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\":\n" +
	"\x15StartContainerRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\"i\n" +
	"\x16ResizeContainerRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x16\n" +
	"\x06height\x18\x02 \x01(\rR\x06height\x12\x14\n" +
	"\x05width\x18\x03 \x01(\rR\x05width\"i\n" +
	"\x16StreamContainerRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x16\n" +
	"\x06height\x18\x02 \x01(\rR\x06height\x12\x14\n" +
	"\x05width\x18\x03 \x01(\rR\x05width\"Q\n" +
	"\x14KillContainerRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x16\n" +
	"\x06signal\x18\x02 \x01(\tR\x06signal\"O\n" +
	"\x17StreamContainerResponse\x12\x1a\n" +
	"\bexitCode\x18\x01 \x01(\x03R\bexitCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\")\n" +
	"\x13CreateVolumeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\")\n" +
	"\x13DeleteVolumeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"n\n" +
	"\x10WriteFileRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12\x1a\n" +
	"\bcontents\x18\x03 \x01(\tR\bcontents\"-\n" +
	"\x10GetImageResponse\x12\x19\n" +
	"\bimage_id\x18\x01 \x01(\tR\aimageId\"\xc2\x03\n" +
	"\x0fContainerConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12@\n" +
	"\aprocess\x18\x03 \x01(\v2&.wabenet.dodo.runtime.v1alpha2.ProcessR\aprocess\x12I\n" +
	"\bterminal\x18\x04 \x01(\v2-.wabenet.dodo.runtime.v1alpha2.TerminalConfigR\bterminal\x12T\n" +
	"\venvironment\x18\x05 \x03(\v22.wabenet.dodo.runtime.v1alpha2.EnvironmentVariableR\venvironment\x12@\n" +
	"\x05ports\x18\x06 \x03(\v2*.wabenet.dodo.runtime.v1alpha2.PortBindingR\x05ports\x12<\n" +
	"\x06mounts\x18\a \x03(\v2$.wabenet.dodo.runtime.v1alpha2.MountR\x06mounts\x12\"\n" +
	"\fcapabilities\x18\b \x03(\tR\fcapabilities\"x\n" +
	"\aProcess\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x1f\n" +
	"\vworking_dir\x18\x02 \x01(\tR\n" +
	"workingDir\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\x03 \x03(\tR\n" +
	"entrypoint\x12\x18\n" +
	"\acommand\x18\x04 \x03(\tR\acommand\"\x82\x01\n" +
	"\x0eTerminalConfig\x12\x14\n" +
	"\x05stdio\x18\x01 \x01(\bR\x05stdio\x12\x10\n" +
	"\x03tty\x18\x02 \x01(\bR\x03tty\x12$\n" +
	"\rconsoleHeight\x18\x03 \x01(\x03R\rconsoleHeight\x12\"\n" +
	"\fconsoleWidth\x18\x04 \x01(\x03R\fconsoleWidth\"=\n" +
	"\x13EnvironmentVariable\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x86\x01\n" +
	"\vPortBinding\x12\x1b\n" +
	"\thost_port\x18\x01 \x01(\tR\bhostPort\x12%\n" +
	"\x0econtainer_port\x18\x02 \x01(\tR\rcontainerPort\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x17\n" +
	"\ahost_ip\x18\x04 \x01(\tR\x06hostIp\"\xe1\x02\n" +
	"\x05Mount\x12>\n" +
	"\x04bind\x18\x01 \x01(\v2(.wabenet.dodo.runtime.v1alpha2.BindMountH\x00R\x04bind\x12D\n" +
	"\x06volume\x18\x02 \x01(\v2*.wabenet.dodo.runtime.v1alpha2.VolumeMountH\x00R\x06volume\x12A\n" +
	"\x05tmpfs\x18\x03 \x01(\v2).wabenet.dodo.runtime.v1alpha2.TmpfsMountH\x00R\x05tmpfs\x12A\n" +
	"\x05image\x18\x04 \x01(\v2).wabenet.dodo.runtime.v1alpha2.ImageMountH\x00R\x05image\x12D\n" +
	"\x06device\x18\x05 \x01(\v2*.wabenet.dodo.runtime.v1alpha2.DeviceMountH\x00R\x06deviceB\x06\n" +
	"\x04type\"k\n" +
	"\tBindMount\x12\x1b\n" +
	"\thost_path\x18\x01 \x01(\tR\bhostPath\x12%\n" +
	"\x0econtainer_path\x18\x02 \x01(\tR\rcontainerPath\x12\x1a\n" +
	"\breadonly\x18\x03 \x01(\bR\breadonly\"\x8b\x01\n" +
	"\vVolumeMount\x12\x1f\n" +
	"\vvolume_name\x18\x01 \x01(\tR\n" +
	"volumeName\x12%\n" +
	"\x0econtainer_path\x18\x02 \x01(\tR\rcontainerPath\x12\x18\n" +
	"\asubpath\x18\x03 \x01(\tR\asubpath\x12\x1a\n" +
	"\breadonly\x18\x04 \x01(\bR\breadonly\"[\n" +
	"\n" +
	"TmpfsMount\x12%\n" +
	"\x0econtainer_path\x18\x01 \x01(\tR\rcontainerPath\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\"\x7f\n" +
	"\n" +
	"ImageMount\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12%\n" +
	"\x0econtainer_path\x18\x02 \x01(\tR\rcontainerPath\x12\x18\n" +
	"\asubpath\x18\x03 \x01(\tR\asubpath\x12\x1a\n" +
	"\breadonly\x18\x04 \x01(\bR\breadonly\"\x94\x01\n" +
	"\vDeviceMount\x12\x1f\n" +
	"\vcgroup_rule\x18\x01 \x01(\tR\n" +
	"cgroupRule\x12\x1b\n" +
	"\thost_path\x18\x02 \x01(\tR\bhostPath\x12%\n" +
	"\x0econtainer_path\x18\x03 \x01(\tR\rcontainerPath\x12 \n" +
	"\vpermissions\x18\x04 \x01(\tR\vpermissions2\xc7\v\n" +
	"\x06Plugin\x12Y\n" +
	"\x11GetPluginMetadata\x12\x16.google.protobuf.Empty\x1a,.wabenet.dodo.plugin.v1alpha2.PluginMetadata\x12V\n" +
	"\n" +
	"InitPlugin\x12\x16.google.protobuf.Empty\x1a0.wabenet.dodo.plugin.v1alpha2.InitPluginResponse\x12=\n" +
	"\vResetPlugin\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12Y\n" +
	"\vStreamInput\x120.wabenet.dodo.plugin.v1alpha2.StreamInputRequest\x1a\x16.google.protobuf.Empty(\x01\x12m\n" +
	"\fStreamOutput\x121.wabenet.dodo.plugin.v1alpha2.StreamOutputRequest\x1a(.wabenet.dodo.plugin.v1alpha2.OutputData0\x01\x12\x80\x01\n" +
	"\x0fCreateContainer\x125.wabenet.dodo.runtime.v1alpha2.CreateContainerRequest\x1a6.wabenet.dodo.runtime.v1alpha2.CreateContainerResponse\x12`\n" +
	"\x0fDeleteContainer\x125.wabenet.dodo.runtime.v1alpha2.DeleteContainerRequest\x1a\x16.google.protobuf.Empty\x12^\n" +
	"\x0eStartContainer\x124.wabenet.dodo.runtime.v1alpha2.StartContainerRequest\x1a\x16.google.protobuf.Empty\x12\x80\x01\n" +
	"\x0fStreamContainer\x125.wabenet.dodo.runtime.v1alpha2.StreamContainerRequest\x1a6.wabenet.dodo.runtime.v1alpha2.StreamContainerResponse\x12`\n" +
	"\x0fResizeContainer\x125.wabenet.dodo.runtime.v1alpha2.ResizeContainerRequest\x1a\x16.google.protobuf.Empty\x12\\\n" +
	"\rKillContainer\x123.wabenet.dodo.runtime.v1alpha2.KillContainerRequest\x1a\x16.google.protobuf.Empty\x12Z\n" +
	"\fCreateVolume\x122.wabenet.dodo.runtime.v1alpha2.CreateVolumeRequest\x1a\x16.google.protobuf.Empty\x12Z\n" +
	"\fDeleteVolume\x122.wabenet.dodo.runtime.v1alpha2.DeleteVolumeRequest\x1a\x16.google.protobuf.Empty\x12T\n" +
	"\tWriteFile\x12/.wabenet.dodo.runtime.v1alpha2.WriteFileRequest\x1a\x16.google.protobuf.Empty\x12k\n" +
	"\bGetImage\x12..wabenet.dodo.runtime.v1alpha2.GetImageRequest\x1a/.wabenet.dodo.runtime.v1alpha2.GetImageResponseB\xa7\x02\n" +
	"!com.wabenet.dodo.runtime.v1alpha2B\fRuntimeProtoP\x01Z]github.com/wabenet/dodo-core/internal/gen-proto/wabenet/dodo/runtime/v1alpha2;runtimev1alpha2\xa2\x02\x03WDR\xaa\x02\x1dWabenet.Dodo.Runtime.V1alpha2\xca\x02\x1dWabenet\\Dodo\\Runtime\\V1alpha2\xe2\x02)Wabenet\\Dodo\\Runtime\\V1alpha2\\GPBMetadata\xea\x02 Wabenet::Dodo::Runtime::V1alpha2b\beditionsp\xe8\a"

var file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_wabenet_dodo_runtime_v1alpha2_runtime_proto_goTypes = []any{
	(*CreateContainerResponse)(nil),      // 0: wabenet.dodo.runtime.v1alpha2.CreateContainerResponse
	(*GetImageRequest)(nil),              // 1: wabenet.dodo.runtime.v1alpha2.GetImageRequest
	(*CreateContainerRequest)(nil),       // 2: wabenet.dodo.runtime.v1alpha2.CreateContainerRequest
	(*DeleteContainerRequest)(nil),       // 3: wabenet.dodo.runtime.v1alpha2.DeleteContainerRequest
	(*StartContainerRequest)(nil),        // 4: wabenet.dodo.runtime.v1alpha2.StartContainerRequest
	(*ResizeContainerRequest)(nil),       // 5: wabenet.dodo.runtime.v1alpha2.ResizeContainerRequest
	(*StreamContainerRequest)(nil),       // 6: wabenet.dodo.runtime.v1alpha2.StreamContainerRequest
	(*KillContainerRequest)(nil),         // 7: wabenet.dodo.runtime.v1alpha2.KillContainerRequest
	(*StreamContainerResponse)(nil),      // 8: wabenet.dodo.runtime.v1alpha2.StreamContainerResponse
	(*CreateVolumeRequest)(nil),          // 9: wabenet.dodo.runtime.v1alpha2.CreateVolumeRequest
	(*DeleteVolumeRequest)(nil),          // 10: wabenet.dodo.runtime.v1alpha2.DeleteVolumeRequest
	(*WriteFileRequest)(nil),             // 11: wabenet.dodo.runtime.v1alpha2.WriteFileRequest
	(*GetImageResponse)(nil),             // 12: wabenet.dodo.runtime.v1alpha2.GetImageResponse
	(*ContainerConfig)(nil),              // 13: wabenet.dodo.runtime.v1alpha2.ContainerConfig
	(*Process)(nil),                      // 14: wabenet.dodo.runtime.v1alpha2.Process
	(*TerminalConfig)(nil),               // 15: wabenet.dodo.runtime.v1alpha2.TerminalConfig
	(*EnvironmentVariable)(nil),          // 16: wabenet.dodo.runtime.v1alpha2.EnvironmentVariable
	(*PortBinding)(nil),                  // 17: wabenet.dodo.runtime.v1alpha2.PortBinding
	(*Mount)(nil),                        // 18: wabenet.dodo.runtime.v1alpha2.Mount
	(*BindMount)(nil),                    // 19: wabenet.dodo.runtime.v1alpha2.BindMount
	(*VolumeMount)(nil),                  // 20: wabenet.dodo.runtime.v1alpha2.VolumeMount
	(*TmpfsMount)(nil),                   // 21: wabenet.dodo.runtime.v1alpha2.TmpfsMount
	(*ImageMount)(nil),                   // 22: wabenet.dodo.runtime.v1alpha2.ImageMount
	(*DeviceMount)(nil),                  // 23: wabenet.dodo.runtime.v1alpha2.DeviceMount
	(*emptypb.Empty)(nil),                // 24: google.protobuf.Empty
	(*v1alpha2.StreamInputRequest)(nil),  // 25: wabenet.dodo.plugin.v1alpha2.StreamInputRequest
	(*v1alpha2.StreamOutputRequest)(nil), // 26: wabenet.dodo.plugin.v1alpha2.StreamOutputRequest
	(*v1alpha2.PluginMetadata)(nil),      // 27: wabenet.dodo.plugin.v1alpha2.PluginMetadata
	(*v1alpha2.InitPluginResponse)(nil),  // 28: wabenet.dodo.plugin.v1alpha2.InitPluginResponse
	(*v1alpha2.OutputData)(nil),          // 29: wabenet.dodo.plugin.v1alpha2.OutputData
}
var file_wabenet_dodo_runtime_v1alpha2_runtime_proto_depIdxs = []int32{
	13, // 0: wabenet.dodo.runtime.v1alpha2.CreateContainerRequest.config:type_name -> wabenet.dodo.runtime.v1alpha2.ContainerConfig
	14, // 1: wabenet.dodo.runtime.v1alpha2.ContainerConfig.process:type_name -> wabenet.dodo.runtime.v1alpha2.Process
	15, // 2: wabenet.dodo.runtime.v1alpha2.ContainerConfig.terminal:type_name -> wabenet.dodo.runtime.v1alpha2.TerminalConfig
	16, // 3: wabenet.dodo.runtime.v1alpha2.ContainerConfig.environment:type_name -> wabenet.dodo.runtime.v1alpha2.EnvironmentVariable
	17, // 4: wabenet.dodo.runtime.v1alpha2.ContainerConfig.ports:type_name -> wabenet.dodo.runtime.v1alpha2.PortBinding
	18, // 5: wabenet.dodo.runtime.v1alpha2.ContainerConfig.mounts:type_name -> wabenet.dodo.runtime.v1alpha2.Mount
	19, // 6: wabenet.dodo.runtime.v1alpha2.Mount.bind:type_name -> wabenet.dodo.runtime.v1alpha2.BindMount
	20, // 7: wabenet.dodo.runtime.v1alpha2.Mount.volume:type_name -> wabenet.dodo.runtime.v1alpha2.VolumeMount
	21, // 8: wabenet.dodo.runtime.v1alpha2.Mount.tmpfs:type_name -> wabenet.dodo.runtime.v1alpha2.TmpfsMount
	22, // 9: wabenet.dodo.runtime.v1alpha2.Mount.image:type_name -> wabenet.dodo.runtime.v1alpha2.ImageMount
	23, // 10: wabenet.dodo.runtime.v1alpha2.Mount.device:type_name -> wabenet.dodo.runtime.v1alpha2.DeviceMount
	24, // 11: wabenet.dodo.runtime.v1alpha2.Plugin.GetPluginMetadata:input_type -> google.protobuf.Empty
	24, // 12: wabenet.dodo.runtime.v1alpha2.Plugin.InitPlugin:input_type -> google.protobuf.Empty
	24, // 13: wabenet.dodo.runtime.v1alpha2.Plugin.ResetPlugin:input_type -> google.protobuf.Empty
	25, // 14: wabenet.dodo.runtime.v1alpha2.Plugin.StreamInput:input_type -> wabenet.dodo.plugin.v1alpha2.StreamInputRequest
	26, // 15: wabenet.dodo.runtime.v1alpha2.Plugin.StreamOutput:input_type -> wabenet.dodo.plugin.v1alpha2.StreamOutputRequest
	2,  // 16: wabenet.dodo.runtime.v1alpha2.Plugin.CreateContainer:input_type -> wabenet.dodo.runtime.v1alpha2.CreateContainerRequest
	3,  // 17: wabenet.dodo.runtime.v1alpha2.Plugin.DeleteContainer:input_type -> wabenet.dodo.runtime.v1alpha2.DeleteContainerRequest
	4,  // 18: wabenet.dodo.runtime.v1alpha2.Plugin.StartContainer:input_type -> wabenet.dodo.runtime.v1alpha2.StartContainerRequest
	6,  // 19: wabenet.dodo.runtime.v1alpha2.Plugin.StreamContainer:input_type -> wabenet.dodo.runtime.v1alpha2.StreamContainerRequest
	5,  // 20: wabenet.dodo.runtime.v1alpha2.Plugin.ResizeContainer:input_type -> wabenet.dodo.runtime.v1alpha2.ResizeContainerRequest
	7,  // 21: wabenet.dodo.runtime.v1alpha2.Plugin.KillContainer:input_type -> wabenet.dodo.runtime.v1alpha2.KillContainerRequest
	9,  // 22: wabenet.dodo.runtime.v1alpha2.Plugin.CreateVolume:input_type -> wabenet.dodo.runtime.v1alpha2.CreateVolumeRequest
	10, // 23: wabenet.dodo.runtime.v1alpha2.Plugin.DeleteVolume:input_type -> wabenet.dodo.runtime.v1alpha2.DeleteVolumeRequest
	11, // 24: wabenet.dodo.runtime.v1alpha2.Plugin.WriteFile:input_type -> wabenet.dodo.runtime.v1alpha2.WriteFileRequest
	1,  // 25: wabenet.dodo.runtime.v1alpha2.Plugin.GetImage:input_type -> wabenet.dodo.runtime.v1alpha2.GetImageRequest
	27, // 26: wabenet.dodo.runtime.v1alpha2.Plugin.GetPluginMetadata:output_type -> wabenet.dodo.plugin.v1alpha2.PluginMetadata
	28, // 27: wabenet.dodo.runtime.v1alpha2.Plugin.InitPlugin:output_type -> wabenet.dodo.plugin.v1alpha2.InitPluginResponse
	24, // 28: wabenet.dodo.runtime.v1alpha2.Plugin.ResetPlugin:output_type -> google.protobuf.Empty
	24, // 29: wabenet.dodo.runtime.v1alpha2.Plugin.StreamInput:output_type -> google.protobuf.Empty
	29, // 30: wabenet.dodo.runtime.v1alpha2.Plugin.StreamOutput:output_type -> wabenet.dodo.plugin.v1alpha2.OutputData
	0,  // 31: wabenet.dodo.runtime.v1alpha2.Plugin.CreateContainer:output_type -> wabenet.dodo.runtime.v1alpha2.CreateContainerResponse
	24, // 32: wabenet.dodo.runtime.v1alpha2.Plugin.DeleteContainer:output_type -> google.protobuf.Empty
	24, // 33: wabenet.dodo.runtime.v1alpha2.Plugin.StartContainer:output_type -> google.protobuf.Empty
	8,  // 34: wabenet.dodo.runtime.v1alpha2.Plugin.StreamContainer:output_type -> wabenet.dodo.runtime.v1alpha2.StreamContainerResponse
	24, // 35: wabenet.dodo.runtime.v1alpha2.Plugin.ResizeContainer:output_type -> google.protobuf.Empty
	24, // 36: wabenet.dodo.runtime.v1alpha2.Plugin.KillContainer:output_type -> google.protobuf.Empty
	24, // 37: wabenet.dodo.runtime.v1alpha2.Plugin.CreateVolume:output_type -> google.protobuf.Empty
	24, // 38: wabenet.dodo.runtime.v1alpha2.Plugin.DeleteVolume:output_type -> google.protobuf.Empty
	24, // 39: wabenet.dodo.runtime.v1alpha2.Plugin.WriteFile:output_type -> google.protobuf.Empty
	12, // 40: wabenet.dodo.runtime.v1alpha2.Plugin.GetImage:output_type -> wabenet.dodo.runtime.v1alpha2.GetImageResponse
	26, // [26:41] is the sub-list for method output_type
	11, // [11:26] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_wabenet_dodo_runtime_v1alpha2_runtime_proto_init() }
func file_wabenet_dodo_runtime_v1alpha2_runtime_proto_init() {
	if File_wabenet_dodo_runtime_v1alpha2_runtime_proto != nil {
		return
	}
	file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes[18].OneofWrappers = []any{
		(*mount_Bind)(nil),
		(*mount_Volume)(nil),
		(*mount_Tmpfs)(nil),
		(*mount_Image)(nil),
		(*mount_Device)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wabenet_dodo_runtime_v1alpha2_runtime_proto_rawDesc), len(file_wabenet_dodo_runtime_v1alpha2_runtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wabenet_dodo_runtime_v1alpha2_runtime_proto_goTypes,
		DependencyIndexes: file_wabenet_dodo_runtime_v1alpha2_runtime_proto_depIdxs,
		MessageInfos:      file_wabenet_dodo_runtime_v1alpha2_runtime_proto_msgTypes,
	}.Build()
	File_wabenet_dodo_runtime_v1alpha2_runtime_proto = out.File
	file_wabenet_dodo_runtime_v1alpha2_runtime_proto_goTypes = nil
	file_wabenet_dodo_runtime_v1alpha2_runtime_proto_depIdxs = nil
}
