---
name: CI

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: "wabenet/wabe-project-build:v0.3.12"
      options: --user runner
    steps:
      - uses: wabenet/project-template/actions/build@v0.3.12

  coverage:
    runs-on: ubuntu-latest
    container:
      image: "wabenet/wabe-project-build:v0.3.12"
      options: --user runner
    steps:
      - uses: wabenet/project-template/actions/coverage@v0.3.12
        with:
          cc-reporter-id: ${{ secrets.CC_TEST_REPORTER_ID }}
