---
name: CI

on: [push, pull_request]

jobs:

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: wabenet/project-template/actions/coverage@v0.3.1
        with:
          go-version: "1.22"
          cc-reporter-id: ${{ secrets.CC_TEST_REPORTER_ID }}
